openapi: 3.2.0
info:
  title: APIs.io Engineering Platform Postman User Provisioning API
  description: "The Postman API enables you to programmatically access data stored in your Postman account.\n\n> Certain endpoints may be unavailable depending on your region and/or Postman plan.\n\nFor a comprehensive set of examples of requests and responses, see the [**Postman API** collection](https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a).\n\n## Getting started\n\nYou can get started with the Postman API by creating a copy of this definition in your workspace.\n\n### EU users\n\nFor users in the EU with [**Enterprise** plans](https://www.postman.com/pricing/), the Postman API uses the `http://api.eu.postman.com` subdomain. This is available in the definition's list of servers. You can change this by selecting the `http://api.eu.postman.com` subdomain in the **Server** dropdown list below.\n\n## About the Postman API\n\n- You must use a valid API Key to send requests to the API endpoints.\n- The API has [rate and usage limits](https://learning.postman.com/docs/developer/postman-api/postman-api-rate-limits/).\n- The API only responds to HTTPS-secured communications. Any requests sent via HTTP return an HTTP `301` redirect to the corresponding HTTPS resources.\n- The API returns requests responses in JSON format. When an API request returns an error, it is sent in the JSON response as an error key.\n- The request method (verb) determines the nature of action you intend to perform. A request made using the `GET` method implies that you want to fetch something from Postman. The `POST` method implies you want to save something new to Postman.\n- For all requests, API calls respond with their corresponding [HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes). In the Postman client, the status code also provides help text that details the possible meaning of the response code.\n- When calling the API Builder endpoints, you must send an `Accept` header with the `application/vnd.api.v10+json` value.\n\n### IDs and UIDs\n\nAll items in Postman, such as collections, workspaces, and APIs, have IDs and UIDs:\n\n- An ID is the unique ID assigned to a Postman item. For example, `ec29121c-5203-409f-9e84-e83ffc10f226`.\n- The UID is the **full** ID of a Postman item. This value is the item's unique ID concatenated with the user ID. For example, in the `12345678-ec29121c-5203-409f-9e84-e83ffc10f226` UID:\n    - `12345678` is the user's ID.\n    - `ec29121c-5203-409f-9e84-e83ffc10f226` is the item's ID.\n\n### Enum values\n\nAny documented enum values should be considered partial lists and may change over time.\n\n### 403 response for unavailable features\n\nDepending on your region and/or Postman [plan](https://www.postman.com/pricing/), some endpoints will return an HTTP `403 Forbidden` response with the \"This feature isn't available in your region.\" detail.\n\n### 503 response\n\nAn HTTP `503 Service Unavailable` response from our servers indicates there is an unexpected spike in API access traffic. The server is usually operational within the next five minutes.\n\nIf the outage persists or you receive any other form of an HTTP `5XX` error, [contact support](https://support.postman.com/hc/en-us/requests/new/).\n\n## Authentication\n\nPostman uses API keys for authentication. The API key tells the API server that the request came from you. Everything that you have access to in Postman is accessible with your API key. You can [generate](https://learning.postman.com/docs/developer/postman-api/authentication/#generate-a-postman-api-key) a Postman API key in the [**API keys**](https://postman.postman.co/settings/me/api-keys) section of your Postman account settings.\n\nYou must include an API key in each request to the Postman API with the `X-API-Key` request header. In Postman, you can store your API key as a [vault secret](https://learning.postman.com/docs/sending-requests/postman-vault/postman-vault-secrets/) or an [environment variable](https://www.getpostman.com/docs/environments). The Postman API [collection](https://www.getpostman.com/docs/collections) will use it to make API calls.\n\n### SCIM authentication\n\nWhile all other endpoints in this collection require a Postman API key, the SCIM endpoints require a [SCIM API key](https://learning.postman.com/docs/administration/scim-provisioning/scim-provisioning-overview/#generating-scim-api-key).\n\n### Authentication error response\n\nIf an API key is missing, malformed, or invalid, you will receive an HTTP `401 Unauthorized` response code.\n\n## Rate and usage limits\n\nAPI access [rate limits](https://learning.postman.com/docs/developer/postman-api/postman-api-rate-limits/) apply at a per-user basis in unit time. The limit is **300 requests per minute**. Postman Monitors, the GET `/collections`, and the GET `/workspaces` endpoint have a rate limit of **10 calls in 10 seconds**. Depending on your [plan](https://www.postman.com/pricing/), you may also have [usage limits](https://learning.postman.com/docs/billing/resource-usage/).\n\nWhen you reach your rate or usage limits, the API returns the following HTTP `429 Too Many Requests` status code with one of the following error responses:\n\n- `rateLimited` — Rate limits reached. The response returns the time after which you can resume calls to the Postman API.\n- `serviceLimitExhausted` — Postman API service limits reached. You will need to contact your Postman Team Admin for assistance.\n\n## Support\n\nFor help regarding accessing the Postman API, you can:\n\n- Visit [Postman Support](https://support.postman.com/hc/en-us) or our [Community and Support](https://www.postman.com/community/) sites.\n- Reach out to the [Postman community](https://community.postman.com/).\n- Submit a help request to [Postman support](https://support.postman.com/hc/en-us/requests/new/).\n\n## Policies\n\n- [Postman Terms of Service](http://www.postman.com/legal/terms/)\n- [Postman Privacy Policy](https://www.postman.com/legal/privacy-policy/)\n"
  version: '1.0'
  termsOfService: https://www.postman.com/legal/terms/
  contact:
    name: Postman Support
    email: help@postman.com
    url: https://www.postman.com/community/
servers:
- url: https://api.getpostman.com
- url: https://api.eu.postman.com
security:
- PostmanApiKey: []
- scimApiKey: []
tags:
- name: User Provisioning
  description: "The **User Provisioning** endpoints enable you to provision and manage your Postman users.\n\n- You can only deactivate users with the SCIM API. You cannot permanently delete users with the API.\n- Users created with the SCIM API are automatically created in Postman:\n  - If the account's email ID does not exist, the user is also added to their organization's Postman team.\n  - If the account's email ID already exists, the system sends the user an email invite to join the Postman team. After they accept the invite, the are added to the team.\n- By default, new users are given the developer role in Postman. Postman user roles cannot be updated via the SCIM API. You must manage user and group roles in Postman.\n"
paths:
  /scim/v2/Users:
    get:
      summary: APIs.io Engineering Platform Get all user resources
      description: Gets information about all Postman team members.
      operationId: getScimUserResources
      x-postman-plan: Enterprise
      tags:
      - User Provisioning
      responses:
        '200':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scimUserResources'
              examples:
                Successful Response:
                  $ref: '#/components/examples/getScimUserResources'
                Filter Inactive Users:
                  $ref: '#/components/examples/getInactiveScimUserResources'
        '400':
          $ref: '#/components/responses/scim400Error'
        '401':
          $ref: '#/components/responses/scim401Error'
        '403':
          $ref: '#/components/responses/scim403Error'
        '500':
          $ref: '#/components/responses/scim500Error'
      parameters:
      - $ref: '#/components/parameters/startIndex'
      - $ref: '#/components/parameters/count'
      - $ref: '#/components/parameters/scimUserFilter'
    post:
      summary: APIs.io Engineering Platform Create a user
      description: 'Creates a new user account in Postman and adds the user to your organization''s Postman team.

        - If the account does not exist, this also activates the user so they can authenticate in to your Postman team.

        - If an account matching the email ID exists, the user receives [email invite](https://learning.postman.com/docs/administration/managing-your-team/manage-team-members/#manage-invites) to join the Postman team. The user joins the team when they accept the invite.

        - If the user''s email domain matches your team''s verified domains, the user is immediately added to the team.


        By default, the system assigns new users the developer role. You can [update user roles in Postman](https://learning.postman.com/docs/administration/managing-your-team/manage-team-members/#manage-team-roles).


        **Note:**


        Users must join the team before you can assign them to any groups.

        '
      operationId: createScimUser
      x-postman-plan: Enterprise
      tags:
      - User Provisioning
      requestBody:
        $ref: '#/components/requestBodies/createScimUser'
      responses:
        '201':
          $ref: '#/components/responses/createScimUser'
        '400':
          $ref: '#/components/responses/scim400ErrorInvalidSyntax'
        '401':
          $ref: '#/components/responses/scim401Error'
        '403':
          $ref: '#/components/responses/scim403Error'
        '409':
          $ref: '#/components/responses/scim409Error'
        '500':
          $ref: '#/components/responses/scim500Error'
  /scim/v2/Users/{userId}:
    parameters:
    - $ref: '#/components/parameters/scimUserId'
    get:
      summary: APIs.io Engineering Platform Get a user resource
      description: Gets information about a Postman team member.
      operationId: getScimUserResource
      x-postman-plan: Enterprise
      tags:
      - User Provisioning
      responses:
        '200':
          $ref: '#/components/responses/scimUserResource'
        '400':
          $ref: '#/components/responses/scim400Error'
        '401':
          $ref: '#/components/responses/scim401Error'
        '403':
          $ref: '#/components/responses/scim403Error'
        '404':
          $ref: '#/components/responses/scim404Error'
        '500':
          $ref: '#/components/responses/scim500ErrorUser'
    put:
      summary: APIs.io Engineering Platform Update a user
      description: 'Updates a user''s first and last name in Postman.


        **Note:**


        You can only use the SCIM API to update a user''s first and last name. You cannot update any other user attributes with the API.

        '
      operationId: updateScimUser
      x-postman-plan: Enterprise
      tags:
      - User Provisioning
      requestBody:
        $ref: '#/components/requestBodies/updateScimUser'
      responses:
        '200':
          $ref: '#/components/responses/scimUserResource'
        '400':
          $ref: '#/components/responses/scim400ErrorInvalidSyntax'
        '401':
          $ref: '#/components/responses/scim401Error'
        '403':
          $ref: '#/components/responses/scim403Error'
        '404':
          $ref: '#/components/responses/scim404Error'
        '500':
          $ref: '#/components/responses/scim500Error'
    patch:
      summary: APIs.io Engineering Platform Update a user's state
      description: 'Updates a user''s active state in Postman.


        **Reactivating a user**


        By setting the `active` property from `false` to `true`, this reactivates an account. This allows the account to authenticate in to Postman and adds the account back on to your Postman team.

        '
      operationId: updateScimUserState
      x-postman-plan: Enterprise
      tags:
      - User Provisioning
      requestBody:
        $ref: '#/components/requestBodies/updateScimUserState'
      responses:
        '200':
          $ref: '#/components/responses/scimUserResource'
        '400':
          $ref: '#/components/responses/scim400ErrorInvalidSyntax'
        '401':
          $ref: '#/components/responses/scim401Error'
        '403':
          $ref: '#/components/responses/scim403Error'
        '404':
          $ref: '#/components/responses/scim404Error'
        '500':
          $ref: '#/components/responses/scim500Error'
components:
  responses:
    scim409Error:
      description: Conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:api:messages:2.0:Error
              scimType:
                type: string
                description: The SCIM error type.
                example: uniqueness
              detail:
                type: string
                description: Information about the error.
                example: This person is already a member of the team.
              status:
                type: string
                format: http-status-code
                description: The HTTP status code.
                example: '409'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            scimType: uniqueness
            detail: This person is already a member of the team.
            status: '409'
    scim500ErrorUser:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:api:messages:2.0:Error
              detail:
                type: string
                description: Information about the error.
                example: Unable to fetch information about this team member.
              status:
                type: string
                format: http-status-code
                description: The HTTP status code.
                example: '500'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            detail: Unable to fetch information about this team member.
            status: '500'
    scim400ErrorInvalidSyntax:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:api:messages:2.0:Error
              scimType:
                type: string
                description: The SCIM error type.
                example: invalidSyntax
              detail:
                type: string
                description: Information about the error.
                example: The request body seems to be incomplete or have unsupported characters.
              status:
                type: string
                format: http-status-code
                description: The HTTP status code.
                example: '400'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            scimType: invalidSyntax
            detail: The request body seems to be incomplete or have unsupported characters.
            status: '400'
    scim500Error:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:api:messages:2.0:Error
              detail:
                type: string
                description: Information about the error.
                example: Couldn't update this team member's information. Try again — it should work next time around.
              status:
                type: string
                format: http-status-code
                description: The HTTP status code.
                example: '500'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            detail: Couldn't update this team member's information. Try again — it should work next time around.
            status: '500'
    scim404Error:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:api:messages:2.0:Error
              detail:
                type: string
                description: Information about the error.
                example: This person isn't a member of the team.
              status:
                type: string
                format: http-status-code
                description: The HTTP status code.
                example: '404'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            detail: This person isn't a member of the team.
            status: '404'
    scim401Error:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:api:messages:2.0:Error
              detail:
                type: string
                description: Information about the error.
                example: Unable to access the team. Check if you have entered a valid API key.
              status:
                type: string
                format: http-status-code
                description: The HTTP status code.
                example: '401'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            detail: Unable to access the team. Check if you have entered a valid API key.
            status: '401'
    scimUserResource:
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:schemas:core:2.0:User
              id:
                type: string
                description: The team member's SCIM ID.
                example: 405775fe15ed41872a8eea4c8aa2b38cda9749812cc55c99
              userName:
                type: string
                description: The team member's SCIM username.
                example: taylor.lee@example.com
              name:
                type: object
                description: Information about the Postman team member.
                properties:
                  givenName:
                    type: string
                    description: The team member's first name.
                    example: Taylor
                  familyName:
                    type: string
                    description: The team member's last name.
                    example: Lee
              externalId:
                type: string
                description: The team member's external ID.
                example: '12345678'
              active:
                type: boolean
                description: If true, the team member is active.
                example: true
              meta:
                type: object
                description: The response's non-standard meta information.
                properties:
                  resourceType:
                    type: string
                    description: The resource type.
                    example: User
                  created:
                    type: string
                    format: date-time
                    description: The date and time at which the team member was created.
                    example: '2021-02-22T04:24:13.000Z'
                  lastModified:
                    type: string
                    format: date-time
                    description: The date and time at which the team member was last modified.
                    example: '2021-02-22T04:24:13.000Z'
          example:
            schemas:
            - urn:ietf:params:scim:schemas:core:2.0:User
            id: 405775fe15ed41872a8eea4c8aa2b38cda9749812cc55c99
            userName: taylor.lee@example.com
            name:
              givenName: Taylor
              familyName: Lee
            externalId: '12345678'
            active: true
            meta:
              resourceType: User
              created: '2021-02-22T04:24:13.000Z'
              lastModified: '2021-02-22T04:24:13.000Z'
    scim400Error:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:api:messages:2.0:Error
              detail:
                type: string
                description: Information about the error.
                example: This Postman team doesn't exist anymore.
              status:
                type: string
                format: http-status-code
                description: The HTTP status code.
                example: '400'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            detail: This Postman team doesn't exist anymore.
            status: '400'
    scim403Error:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:api:messages:2.0:Error
              detail:
                type: string
                description: Information about the error.
                example: Your API key was generated by a Team Admin who is no longer on your team. Use an API key generated by a Team Admin.
              status:
                type: string
                format: http-status-code
                description: The HTTP status code.
                example: '403'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            detail: Your API key was generated by a Team Admin who is no longer on your team. Use an API key generated by a Team Admin.
            status: '403'
    createScimUser:
      description: Created
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:schemas:core:2.0:User
              id:
                type: string
                description: The user's SCIM ID.
                example: 405775fe15ed41872a8eea4c8aa2b38cda9749812cc55c99
              userName:
                type: string
                format: email
                description: The user's username.
                example: taylor.lee@example.com
              name:
                type: object
                properties:
                  givenName:
                    type: string
                    description: The user's first name.
                    example: Taylor
                  familyName:
                    type: string
                    description: The user's last name.
                    example: Lee
              externalId:
                type: string
                description: The user's external ID.
                example: '12345678'
              active:
                type: boolean
                description: If true, the user is active.
                example: true
              meta:
                type: object
                description: The response's non-standard meta information.
                properties:
                  created:
                    type: string
                    format: date-time
                    description: The date and time at which the user was created.
                    example: '2021-02-22T04:24:13.000Z'
                  lastModified:
                    type: string
                    format: date-time
                    description: The date and time at which the user was last modified.
                    example: '2021-02-22T04:24:13.000Z'
                  resourceType:
                    type: string
                    description: The SCIM resource type.
                    enum:
                    - User
                    example: User
          example:
            schemas:
            - urn:ietf:params:scim:schemas:core:2.0:User
            id: 405775fe15ed41872a8eea4c8aa2b38cda9749812cc55c99
            userName: taylor.lee@example.com
            name:
              givenName: Test
              familyName: User
            externalId: '12345678'
            active: true
            meta:
              resourceType: User
              created: '2021-02-22T04:24:13.000Z'
              lastModified: '2021-02-22T04:24:13.000Z'
  parameters:
    count:
      name: count
      in: query
      description: Limit the number of results returned in a single response.
      schema:
        type: number
        default: 100
        example: 2
    startIndex:
      name: startIndex
      in: query
      description: The index entry by which to begin the list of returned results.
      schema:
        type: number
        default: 1
        example: 1
    scimUserFilter:
      name: filter
      in: query
      description: 'Filter results by a specific word or phrase. This query parameter accepts the following:

        - `userName` — Filter values are case-sensitive, and special characters and spaces must be URL encoded.

        - `active` — Return only users who are active (`true`) or inactive (`false`).

        '
      schema:
        type: string
        example: userName eq "taylor-lee%40example.com"
      examples:
        Filter:
          value: userName eq "taylor-lee%40example.com"
        Filter with Encoding:
          value: userName eq "taylor-lee%2Btest%40example.com"
        Filter Active Users:
          value: active eq "true"
        Filter Inactive Users:
          value: active eq "false"
    scimUserId:
      name: userId
      in: path
      required: true
      description: The user's SCIM ID.
      schema:
        $ref: '#/components/schemas/scimId'
  examples:
    getInactiveScimUserResources:
      value:
        schemas:
        - urn:ietf:params:scim:api:messages:2.0:ListResponse
        totalResults: 1
        startIndex: 1
        itemsPerPage: 2
        Resources:
        - schemas:
          - urn:ietf:params:scim:schemas:core:2.0:User
          id: 123775fe15ed41872a8eea4c8aa2b38cda9749812cc55c99
          userName: alex.cruz@example.com
          name:
            givenName: Alex
            familyName: Cruz
          externalId: '87654321'
          active: false
          meta:
            resourceType: User
            created: '2021-02-22T04:24:13.000Z'
            lastModified: '2021-02-22T04:24:13.000Z'
    getScimUserResources:
      value:
        schemas:
        - urn:ietf:params:scim:api:messages:2.0:ListResponse
        totalResults: 2
        startIndex: 1
        itemsPerPage: 2
        Resources:
        - schemas:
          - urn:ietf:params:scim:schemas:core:2.0:User
          id: 405775fe15ed41872a8eea4c8aa2b38cda9749812cc55c99
          userName: taylor.lee@example.com
          name:
            givenName: Taylor
            familyName: Lee
          externalId: '12345678'
          active: true
          meta:
            resourceType: User
            created: '2021-02-22T04:24:13.000Z'
            lastModified: '2021-02-22T04:24:13.000Z'
        - schemas:
          - urn:ietf:params:scim:schemas:core:2.0:User
          id: 123775fe15ed41872a8eea4c8aa2b38cda9749812cc55c99
          userName: alex.cruz@example.com
          name:
            givenName: Alex
            familyName: Cruz
          externalId: '87654321'
          active: false
          meta:
            resourceType: User
            created: '2021-02-22T04:24:13.000Z'
            lastModified: '2021-02-22T04:24:13.000Z'
  schemas:
    scimId:
      type: string
      example: 405775fe15ed41872a8eea4c8aa2b38cda9749812cc55c99
    scimUserResource:
      title: SCIM User Resource
      description: The SCIM user resource object.
      type: object
      properties:
        schemas:
          type: array
          description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
          items:
            type: string
            example: urn:ietf:params:scim:schemas:core:2.0:User
        id:
          type: string
          description: The team member's SCIM ID.
          example: 405775fe15ed41872a8eea4c8aa2b38cda9749812cc55c99
        userName:
          type: string
          description: The team member's SCIM username.
          example: taylor.lee@example.com
        name:
          type: object
          description: Information about the Postman team member.
          properties:
            givenName:
              type: string
              description: The team member's first name.
              example: Taylor
            familyName:
              type: string
              description: The team member's last name.
              example: Lee
        externalId:
          type: string
          description: The team member's external ID.
          example: '12345678'
        active:
          type: boolean
          description: If true, the team member is active.
          example: true
        meta:
          type: object
          description: The response's non-standard meta information.
          properties:
            resourceType:
              type: string
              description: The resource type.
              example: User
            created:
              type: string
              format: date-time
              description: The date and time at which the team member was created.
              example: '2021-02-22T04:24:13.000Z'
            lastModified:
              type: string
              format: date-time
              description: The date and time at which the team member was last modified.
              example: '2021-02-22T04:24:13.000Z'
    scimUserResources:
      title: SCIM Users
      type: object
      properties:
        Resources:
          type: array
          description: A list of user resources.
          items:
            $ref: '#/components/schemas/scimUserResource'
        itemsPerPage:
          type: number
          description: The number of items per response page.
          example: 2
        schemas:
          type: array
          items:
            type: string
            description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
            example: urn:ietf:params:scim:api:messages:2.0:ListResponse
        startIndex:
          type: number
          description: The index entry by which the returned results begin.
          example: 1
        totalResults:
          type: number
          description: The total number of results found.
          example: 1000
  requestBodies:
    updateScimUser:
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:schemas:core:2.0:User
              name:
                type: object
                description: Information about the user's name.
                properties:
                  givenName:
                    type: string
                    description: The user's first name.
                    example: Taylor
                  familyName:
                    type: string
                    description: The user's last name.
                    example: Lee
          example:
            schemas:
            - urn:ietf:params:scim:schemas:core:2.0:User
            name:
              givenName: Taylor
              familyName: Lee
    createScimUser:
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:schemas:core:2.0:User
              userName:
                type: string
                description: The user's username.
                example: taylor.lee@example.com
              active:
                type: boolean
                description: If true, activates the user. This lets them authenticate in to your Postman team.
                example: true
              externalId:
                type: string
                description: The user's external ID.
                example: '12345678'
              groups:
                type: array
                description: A list of groups to assign the user to.
                items:
                  type: string
                  example: Test Group
              locale:
                type: string
                description: The user's [IETF language tag](https://datatracker.ietf.org/doc/html/rfc5646).
                example: en-US
              name:
                type: object
                description: Information about the user's name.
                properties:
                  givenName:
                    type: string
                    description: The user's first name.
                    example: Taylor
                  familyName:
                    type: string
                    description: The user's last name.
                    example: Lee
          example:
            schemas:
            - urn:ietf:params:scim:schemas:core:2.0:User
            userName: taylor.lee@example.com
            name:
              givenName: Taylor
              familyName: Lee
            displayName: Taylor Lee
            locale: en-US
            groups:
            - Test Group
            active: true
    updateScimUserState:
      content:
        application/json:
          schema:
            type: object
            properties:
              schemas:
                type: array
                description: The [SCIM schema URI](https://www.iana.org/assignments/scim/scim.xhtml).
                items:
                  type: string
                  example: urn:ietf:params:scim:api:messages:2.0:PatchOp
              Operations:
                type: array
                description: Information about the user update operation.
                items:
                  type: object
                  properties:
                    op:
                      type: string
                      description: The operation to perform.
                      enum:
                      - replace
                      example: replace
                    value:
                      type: object
                      description: The performed operation's value.
                      properties:
                        active:
                          type: boolean
                          description: 'Sets the user''s `active` state:

                            - `true` — Activates the user. This lets them authenticate in to your Postman team.

                            - `false` — Removes the user from your Postman team and deactivates the account. This blocks the user from authenticating in to Postman.

                            '
                          example: true
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:PatchOp
            Operations:
            - op: replace
              value:
                active: true
  securitySchemes:
    PostmanApiKey:
      type: apiKey
      in: header
      name: x-api-key
    scimApiKey:
      type: apiKey
      in: header
      name: Authorization
      description: A valid [SCIM API key](https://learning.postman.com/docs/administration/scim-provisioning/scim-provisioning-overview/#generating-scim-api-key) for calls to SCIM endpoints.
