openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare R2 Event Notification API
  version: 4.0.0
tags:
- name: R2 Event Notification
paths:
  /accounts/{account_id}/event_notifications/r2/{bucket_name}/configuration:
    get:
      description: Returns all notification rules for each queue for which bucket notifications are produced.
      operationId: event-notification-get-r2-bucket-configs
      parameters:
      - in: path
        name: bucket_name
        required: true
        schema:
          $ref: '#/components/schemas/mq_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mq_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mq_api-response-common-failure'
          description: Read Configuration failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/mq_api-response-common'
                - properties:
                    result:
                      $ref: '#/components/schemas/mq_bucket-config'
                  type: object
          description: Read Configuration response
        '404':
          content:
            application/json:
              example:
                errors:
                - code: 11015
                  message: workers.api.error.no_configs_found_for_bucket
                messages: []
                result: null
                success: false
              schema:
                $ref: '#/components/schemas/mq_api-response-common-failure'
          description: No Configuration Found response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Read Configuration
      tags:
      - R2 Event Notification
      x-api-token-group:
      - Workers R2 Storage Read
  /accounts/{account_id}/event_notifications/r2/{bucket_name}/configuration/queues/{queue_id}:
    delete:
      description: Turn off all event notifications configured for delivery to a given queue. No further notifications will be produced for the queue once complete.
      operationId: event-notification-delete-queue-config
      parameters:
      - in: path
        name: queue_id
        required: true
        schema:
          $ref: '#/components/schemas/mq_identifier'
      - in: path
        name: bucket_name
        required: true
        schema:
          $ref: '#/components/schemas/mq_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mq_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mq_api-response-common-failure'
          description: Create Configuration failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mq_api-response-common'
          description: Delete Configuration response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Delete Configuration
      tags:
      - R2 Event Notification
    put:
      description: Define the rules for a given queue which will determine event notification production.
      operationId: event-notification-create-queue-config
      parameters:
      - in: path
        name: queue_id
        required: true
        schema:
          $ref: '#/components/schemas/mq_identifier'
      - in: path
        name: bucket_name
        required: true
        schema:
          $ref: '#/components/schemas/mq_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mq_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                rules:
                  description: Array of rules to drive notifications
                  items:
                    $ref: '#/components/schemas/mq_rule'
                  type: array
              type: object
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mq_api-response-common-failure'
          description: Create Configuration failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/mq_api-response-common'
                - properties:
                    result:
                      properties:
                        event_notification_detail_id:
                          example: deadbeef-1234-4e81-5678-abadfeedbead
                          type: string
                      type: object
                  type: object
          description: Create Configuration response
        '409':
          content:
            application/json:
              example:
                errors:
                - code: 11010
                  message: workers.api.error.event_notification_detail_exists
                messages: []
                result: null
                success: false
              schema:
                $ref: '#/components/schemas/mq_api-response-common-failure'
          description: Duplicate Configuration failure
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Create Configuration
      tags:
      - R2 Event Notification
components:
  schemas:
    mq_detail:
      properties:
        queue:
          description: Queue ID that will receive notifications based on the configured rules
          example: 98fa6c35-dead-beef-a42b-8d12196e0000
          type: string
        rules:
          description: Array of rules to drive notifications
          items:
            $ref: '#/components/schemas/mq_rule'
          type: array
      required:
      - queue
      - rules
      type: object
    mq_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/mq_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/mq_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful.
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    mq_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/mq_messages'
        messages:
          $ref: '#/components/schemas/mq_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful.
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    mq_bucket-config:
      additionalProperties:
        $ref: '#/components/schemas/mq_config-detail'
      example:
        my-bucket:
          b588b5d5-0647-4e81-bb8c-800fad2239a0:
            queue: 98fa6c35-dead-beef-a42b-8d12196e0000
            rules:
            - actions:
              - PutObject
              - DeleteObject
              prefix: img/
              suffix: .jpg
          deadbeef-1234-4e81-5678-abadfeedbead:
            queue: 11111111-dead-beef-0000-109238eeffff
            rules:
            - actions:
              - CopyObject
              suffix: .mov
      type: object
    mq_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    mq_config-detail:
      additionalProperties:
        $ref: '#/components/schemas/mq_detail'
      type: object
    mq_r2-action:
      enum:
      - PutObject
      - CopyObject
      - DeleteObject
      - CompleteMultipartUpload
      - AbortMultipartUpload
      type: string
    mq_rule:
      properties:
        actions:
          description: Array of R2 object actions that will trigger notifications
          example:
          - PutObject
          - CopyObject
          items:
            $ref: '#/components/schemas/mq_r2-action'
          type: array
          uniqueItems: true
        prefix:
          description: Notifications will be sent only for objects with this prefix
          example: img/
          type: string
        suffix:
          description: Notifications will be sent only for objects with this suffix
          example: .jpeg
          type: string
      required:
      - actions
      type: object
    mq_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
