openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Load Balancer Healthcheck Events API
  version: 4.0.0
tags:
- name: Load Balancer Healthcheck Events
paths:
  /user/load_balancing_analytics/events:
    get:
      description: List origin health changes.
      operationId: load-balancer-healthcheck-events-list-healthcheck-events
      parameters:
      - in: query
        name: until
        schema:
          $ref: '#/components/schemas/load-balancing_until'
      - in: query
        name: pool_name
        schema:
          $ref: '#/components/schemas/load-balancing_pool_name'
      - in: query
        name: origin_healthy
        schema:
          $ref: '#/components/schemas/load-balancing_origin_healthy'
      - in: query
        name: pool_id
        schema:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
      - in: query
        name: since
        schema:
          description: Start date and time of requesting data period in the ISO8601 format.
          example: '2016-11-11T12:00:00Z'
          format: date-time
          type: string
      - in: query
        name: origin_name
        schema:
          description: The name for the origin to filter.
          example: primary-dc-1
          type: string
      - in: query
        name: pool_healthy
        schema:
          default: true
          description: If true, filter events where the pool status is healthy. If false, filter events where the pool status is unhealthy.
          example: true
          type: boolean
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_components-schemas-response_collection'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: List Healthcheck Events response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_components-schemas-response_collection'
          description: List Healthcheck Events response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Healthcheck Events
      tags:
      - Load Balancer Healthcheck Events
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Read'
components:
  schemas:
    load-balancing_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    load-balancing_until:
      description: End date and time of requesting data period in the ISO8601 format.
      example: '2016-11-11T13:00:00Z'
      format: date-time
      type: string
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    load-balancing_pool_name:
      description: The name for the pool to filter.
      example: primary-dc
      type: string
    load-balancing_origin-healthy:
      description: Whether the origin is reported as healthy.
      example: true
      type: boolean
    load-balancing_origin_healthy:
      default: true
      description: If true, filter events where the origin status is healthy. If false, filter events where the origin status is unhealthy.
      example: true
      type: boolean
    load-balancing_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    load-balancing_origin-changed:
      description: Whether the origin has changed health status.
      example: true
      type: boolean
    load-balancing_components-schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/load-balancing_analytics'
            type: array
    load-balancing_schemas-identifier:
      example: 17b5962d775c646f3f9725cbc7a53df4
      type: string
    load-balancing_analytics:
      properties:
        id:
          default: 1
          type: integer
        origins:
          example:
          - address: 198.51.100.4
            changed: true
            enabled: true
            failure_reason: No failures
            healthy: true
            ip: 198.51.100.4
            name: some-origin
          items:
            $ref: '#/components/schemas/load-balancing_origin-analytics'
          type: array
        pool:
          example:
            changed: true
            healthy: true
            id: 74bc6a8b9b0dda3d651707a2928bad0c
            minimum_origins: 1
            name: some-pool
          type: object
        timestamp:
          example: '2014-01-01T05:20:00.12345Z'
          format: date-time
          type: string
      type: object
    load-balancing_origin-ip:
      description: The IP address (IPv4 or IPv6) of the origin.
      example: 198.51.100.4
      type: string
    load-balancing_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/load-balancing_result_info'
      type: object
    load-balancing_origin-failure-reason:
      description: Failure reason for un-healthy origin health check.
      example: No failures
      type: string
    load-balancing_origin-analytics:
      properties:
        address:
          $ref: '#/components/schemas/load-balancing_address'
        changed:
          $ref: '#/components/schemas/load-balancing_origin-changed'
        enabled:
          $ref: '#/components/schemas/load-balancing_schemas-enabled'
        failure_reason:
          $ref: '#/components/schemas/load-balancing_origin-failure-reason'
        healthy:
          $ref: '#/components/schemas/load-balancing_origin-healthy'
        ip:
          $ref: '#/components/schemas/load-balancing_origin-ip'
        name:
          $ref: '#/components/schemas/load-balancing_schemas-name'
      type: object
    load-balancing_schemas-name:
      description: A human-identifiable name for the origin.
      example: app-server-1
      type: string
    load-balancing_schemas-enabled:
      default: true
      description: Whether to enable (the default) this origin within the pool. Disabled origins will not receive traffic and are excluded from health checks. The origin will only be disabled for the current pool.
      example: true
      type: boolean
    load-balancing_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/load-balancing_messages'
        messages:
          $ref: '#/components/schemas/load-balancing_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    load-balancing_address:
      description: The IP address (IPv4 or IPv6) of the origin, or its publicly addressable hostname. Hostnames entered here should resolve directly to the origin, and not be a hostname proxied by Cloudflare. To set an internal/reserved address, virtual_network_id must also be set.
      example: 0.0.0.0
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
