openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Pages Deployment API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Pages Deployment
paths:
  /accounts/{account_id}/pages/projects/{project_name}/deployments:
    get:
      description: Fetch a list of project deployments.
      operationId: pages-deployment-get-deployments
      parameters:
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      - in: query
        name: env
        schema:
          description: What type of deployments to fetch.
          enum:
          - production
          - preview
          example: preview
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_deployment-list-response'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Get deployments response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_deployment-list-response'
          description: Get deployments response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get deployments
      tags:
      - Pages Deployment
    post:
      description: Start a new deployment from production. The repository and account must have already been authorized on the Cloudflare Pages dashboard.
      operationId: pages-deployment-create-deployment
      parameters:
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                branch:
                  description: The branch to build the new deployment from. The `HEAD` of the branch will be used. If omitted, the production branch will be used by default.
                  example: staging
                  type: string
              type: object
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_deployment-new-deployment'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Create deployment response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_deployment-new-deployment'
          description: Create deployment response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create deployment
      tags:
      - Pages Deployment
  /accounts/{account_id}/pages/projects/{project_name}/deployments/{deployment_id}:
    delete:
      description: Delete a deployment.
      operationId: pages-deployment-delete-deployment
      parameters:
      - in: path
        name: deployment_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - example:
                    errors: []
                    messages: []
                    result: null
                    success: true
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Delete deployment response failure.
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_api-response-common'
                - properties:
                    result:
                      nullable: true
                      type: object
                  type: object
          description: Delete deployment response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete deployment
      tags:
      - Pages Deployment
    get:
      description: Fetch information about a deployment.
      operationId: pages-deployment-get-deployment-info
      parameters:
      - in: path
        name: deployment_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_deployment-response-details'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Get deployment info response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_deployment-response-details'
          description: Get deployment info response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get deployment info
      tags:
      - Pages Deployment
  /accounts/{account_id}/pages/projects/{project_name}/deployments/{deployment_id}/history/logs:
    get:
      description: Fetch deployment logs for a project.
      operationId: pages-deployment-get-deployment-logs
      parameters:
      - in: path
        name: deployment_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_deployment-response-logs'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Get deployment logs response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_deployment-response-logs'
          description: Get deployment logs response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get deployment logs
      tags:
      - Pages Deployment
  /accounts/{account_id}/pages/projects/{project_name}/deployments/{deployment_id}/retry:
    post:
      description: Retry a previous deployment.
      operationId: pages-deployment-retry-deployment
      parameters:
      - in: path
        name: deployment_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_deployment-new-deployment'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Retry deployment response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_deployment-new-deployment'
          description: Retry deployment response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Retry deployment
      tags:
      - Pages Deployment
  /accounts/{account_id}/pages/projects/{project_name}/deployments/{deployment_id}/rollback:
    post:
      description: Rollback the production deployment to a previous deployment. You can only rollback to succesful builds on production.
      operationId: pages-deployment-rollback-deployment
      parameters:
      - in: path
        name: deployment_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_deployment-response-details'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Rollback deployment response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_deployment-response-details'
          description: Rollback deployment response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Rollback deployment
      tags:
      - Pages Deployment
components:
  schemas:
    pages_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/pages_messages'
          example:
          - code: 7003
            message: No route for the URI.
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/pages_messages'
          example: []
        result:
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    pages_deployment-response-details:
      allOf:
      - $ref: '#/components/schemas/pages_api-response-common'
      - properties:
          result:
            $ref: '#/components/schemas/pages_deployments'
    pages_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/pages_messages'
        messages:
          $ref: '#/components/schemas/pages_messages'
        success:
          description: Whether the API call was successful
          enum:
          - false
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    pages_deployment-response-logs:
      allOf:
      - $ref: '#/components/schemas/pages_api-response-common'
      - properties:
          result:
            example:
              data:
              - line: Cloning repository...
                ts: '2021-04-20T19:35:29.0749819Z'
              - line: From https://github.com/cloudflare/example
                ts: '2021-04-20T19:35:30.0749819Z'
              - line: ' * branch            209c5bb11d89533f426b2f8469bcae12fdccf71b -> FETCH_HEAD'
                ts: '2021-04-20T19:35:30.0749819Z'
              - line: ''
                ts: '2021-04-20T19:35:30.0749819Z'
              - line: HEAD is now at 209c5bb Update index.html
                ts: '2021-04-20T19:35:30.0749819Z'
              - line: ''
                ts: '2021-04-20T19:35:30.0749819Z'
              - line: ''
                ts: '2021-04-20T19:35:30.0749819Z'
              - line: 'Success: Finished cloning repository files'
                ts: '2021-04-20T19:35:30.0749819Z'
              - line: Installing dependencies
                ts: '2021-04-20T19:35:59.0749819Z'
              - line: Python version set to 2.7
                ts: '2021-04-20T19:35:59.0931208Z'
              - line: v12.18.0 is already installed.
                ts: '2021-04-20T19:36:02.2369501Z'
              - line: Now using node v12.18.0 (npm v6.14.4)
                ts: '2021-04-20T19:36:02.6028886Z'
              - line: Started restoring cached build plugins
                ts: '2021-04-20T19:36:02.624555Z'
              - line: Finished restoring cached build plugins
                ts: '2021-04-20T19:36:02.6340688Z'
              - line: Attempting ruby version 2.7.1, read from environment
                ts: '2021-04-20T19:36:02.963095Z'
              - line: Using ruby version 2.7.1
                ts: '2021-04-20T19:36:04.2236084Z'
              - line: Using PHP version 5.6
                ts: '2021-04-20T19:36:04.5450152Z'
              - line: 5.2 is already installed.
                ts: '2021-04-20T19:36:04.5740509Z'
              - line: Using Swift version 5.2
                ts: '2021-04-20T19:36:04.577035Z'
              - line: Installing Hugo 0.54.0
                ts: '2021-04-20T19:36:04.5771615Z'
              - line: 'Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z'
                ts: '2021-04-20T19:36:05.4786868Z'
              - line: Started restoring cached go cache
                ts: '2021-04-20T19:36:05.4794366Z'
              - line: Finished restoring cached go cache
                ts: '2021-04-20T19:36:05.481977Z'
              - line: go version go1.14.4 linux/amd64
                ts: '2021-04-20T19:36:05.9049776Z'
              - line: go version go1.14.4 linux/amd64
                ts: '2021-04-20T19:36:05.9086053Z'
              - line: Installing missing commands
                ts: '2021-04-20T19:36:05.9163568Z'
              - line: Verify run directory
                ts: '2021-04-20T19:36:05.9163934Z'
              - line: 'Executing user command: echo "skipping build step: no build command specified"'
                ts: '2021-04-20T19:36:05.9164636Z'
              - line: 'skipping build step: no build command specified'
                ts: '2021-04-20T19:36:05.9165087Z'
              - line: Finished
                ts: '2021-04-20T19:36:05.917412Z'
              includes_container_logs: true
              total: 30
            properties:
              data:
                items:
                  properties:
                    line:
                      readOnly: true
                      type: string
                    ts:
                      readOnly: true
                      type: string
                  type: object
                type: array
              includes_container_logs:
                readOnly: true
                type: boolean
              total:
                readOnly: true
                type: integer
            type: object
        type: object
    pages_deployments:
      properties:
        aliases:
          description: A list of alias URLs pointing to this deployment.
          example:
          - https://branchname.projectname.pages.dev
          items:
            type: string
          nullable: true
          readOnly: true
          type: array
        build_config:
          $ref: '#/components/schemas/pages_build_config'
        created_on:
          description: When the deployment was created.
          example: '2021-03-09T00:55:03.923456Z'
          format: date-time
          readOnly: true
          type: string
        deployment_trigger:
          description: Info about what caused the deployment.
          properties:
            metadata:
              description: Additional info about the trigger.
              properties:
                branch:
                  description: Where the trigger happened.
                  example: main
                  readOnly: true
                  type: string
                commit_hash:
                  description: Hash of the deployment trigger commit.
                  example: ad9ccd918a81025731e10e40267e11273a263421
                  readOnly: true
                  type: string
                commit_message:
                  description: Message of the deployment trigger commit.
                  example: Update index.html
                  readOnly: true
                  type: string
              type: object
            type:
              description: What caused the deployment.
              example: ad_hoc
              pattern: push|ad_hoc
              readOnly: true
              type: string
          readOnly: true
          type: object
        env_vars:
          additionalProperties:
            description: Environment variable.
            nullable: true
            properties:
              type:
                description: The type of environment variable.
                type: string
              value:
                description: Environment variable value.
                type: string
            required:
            - value
            type: object
          description: A dict of env variables to build this deploy.
          example:
            BUILD_VERSION:
              value: '3.3'
            ENV:
              value: STAGING
          readOnly: true
          type: object
        environment:
          description: Type of deploy.
          example: preview
          pattern: preview|production
          readOnly: true
          type: string
        id:
          description: Id of the deployment.
          example: f64788e9-fccd-4d4a-a28a-cb84f88f6
          readOnly: true
          type: string
        is_skipped:
          description: If the deployment has been skipped.
          example: true
          readOnly: true
          type: boolean
        latest_stage:
          $ref: '#/components/schemas/pages_stage'
        modified_on:
          description: When the deployment was last modified.
          example: 2021-03-09 00:58:59.045655
          format: date-time
          readOnly: true
          type: string
        project_id:
          description: Id of the project.
          example: 7b162ea7-7367-4d67-bcde-1160995d5
          readOnly: true
          type: string
        project_name:
          description: Name of the project.
          example: ninjakittens
          readOnly: true
          type: string
        short_id:
          description: Short Id (8 character) of the deployment.
          example: f64788e9
          readOnly: true
          type: string
        source:
          $ref: '#/components/schemas/pages_source'
        stages:
          description: List of past stages.
          example:
          - ended_on: '2021-06-03T15:39:03.134378Z'
            name: queued
            started_on: '2021-06-03T15:38:15.608194Z'
            status: active
          - ended_on: null
            name: initialize
            started_on: null
            status: idle
          - ended_on: null
            name: clone_repo
            started_on: null
            status: idle
          - ended_on: null
            name: build
            started_on: null
            status: idle
          - ended_on: null
            name: deploy
            started_on: null
            status: idle
          items:
            $ref: '#/components/schemas/pages_stage'
          readOnly: true
          type: array
        url:
          description: The live URL to view this deployment.
          example: https://f64788e9.ninjakittens.pages.dev
          readOnly: true
          type: string
      type: object
    pages_api-response-pagination:
      properties:
        result_info:
          properties:
            count:
              description: The number of items on the current page.
              example: 1
              type: integer
            page:
              description: The page currently being requested.
              example: 1
              type: integer
            per_page:
              description: The number of items per page being returned.
              example: 100
              type: integer
            total_count:
              description: The total count of items.
              example: 1
              type: integer
            total_pages:
              description: The total count of pages.
              example: 1
              type: integer
          required:
          - page
          - per_page
          - count
          - total_count
          type: object
      type: object
    pages_source:
      properties:
        config:
          properties:
            deployments_enabled:
              type: boolean
            owner:
              type: string
            path_excludes:
              items:
                type: string
              type: array
            path_includes:
              items:
                type: string
              type: array
            pr_comments_enabled:
              type: boolean
            preview_branch_excludes:
              items:
                type: string
              type: array
            preview_branch_includes:
              items:
                type: string
              type: array
            preview_deployment_setting:
              enum:
              - all
              - none
              - custom
              type: string
            production_branch:
              type: string
            production_deployments_enabled:
              type: boolean
            repo_name:
              type: string
          type: object
        type:
          type: string
      readOnly: true
      type: object
    pages_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    pages_project_name:
      description: Name of the project.
      example: this-is-my-project-01
      pattern: ^[a-z0-9][a-z0-9-]*$
      type: string
    pages_deployment-new-deployment:
      allOf:
      - $ref: '#/components/schemas/pages_api-response-common'
      - properties:
          result:
            $ref: '#/components/schemas/pages_deployments'
    pages_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    pages_build_config:
      description: Configs for the project build process.
      properties:
        build_caching:
          description: Enable build caching for the project.
          example: true
          nullable: true
          type: boolean
        build_command:
          description: Command used to build project.
          example: npm run build
          nullable: true
          type: string
        destination_dir:
          description: Output directory of the build.
          example: build
          nullable: true
          type: string
        root_dir:
          description: Directory to run the command.
          example: /
          nullable: true
          type: string
        web_analytics_tag:
          description: The classifying tag for analytics.
          example: cee1c73f6e4743d0b5e6bb1a0bcaabcc
          nullable: true
          type: string
        web_analytics_token:
          description: The auth token for analytics.
          example: 021e1057c18547eca7b79f2516f06o7x
          nullable: true
          type: string
      type: object
    pages_stage:
      description: The status of the deployment.
      properties:
        ended_on:
          description: When the stage ended.
          example: 2021-03-09 00:58:59.045655
          format: date-time
          nullable: true
          readOnly: true
          type: string
        name:
          description: The current build stage.
          example: deploy
          pattern: queued|initialize|clone_repo|build|deploy
          type: string
        started_on:
          description: When the stage started.
          example: '2021-03-09T00:55:03.923456Z'
          format: date-time
          nullable: true
          readOnly: true
          type: string
        status:
          description: State of the current stage.
          example: success
          pattern: success|idle|active|failure|canceled
          readOnly: true
          type: string
      readOnly: true
      type: object
    pages_deployment-list-response:
      allOf:
      - $ref: '#/components/schemas/pages_api-response-common'
      - $ref: '#/components/schemas/pages_api-response-pagination'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/pages_deployments'
            type: array
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
