openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Diagnostics API
  version: 4.0.0
tags:
- name: Diagnostics
paths:
  /accounts/{account_id}/diagnostics/traceroute:
    post:
      description: Run traceroutes from Cloudflare colos.
      operationId: diagnostics-traceroute
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic-transit_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                colos:
                  $ref: '#/components/schemas/magic-transit_colos'
                options:
                  $ref: '#/components/schemas/magic-transit_options'
                targets:
                  $ref: '#/components/schemas/magic-transit_targets'
              required:
              - targets
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/magic-transit_traceroute_response_collection'
                - $ref: '#/components/schemas/magic-transit_api-response-common-failure'
          description: Traceroute response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic-transit_traceroute_response_collection'
          description: Traceroute response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Traceroute
      tags:
      - Diagnostics
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic-transit_options:
      example:
        max_ttl: 15
        packet_type: icmp
      properties:
        max_ttl:
          $ref: '#/components/schemas/magic-transit_max_ttl'
        packet_type:
          $ref: '#/components/schemas/magic-transit_packet_type'
        packets_per_ttl:
          $ref: '#/components/schemas/magic-transit_packets_per_ttl'
        port:
          $ref: '#/components/schemas/magic-transit_port'
        wait_time:
          $ref: '#/components/schemas/magic-transit_wait_time'
    magic-transit_asn:
      description: AS number associated with the node object.
      type: string
    magic-transit_node_result:
      example:
        asn: AS13335
        ip: 1.1.1.1
        max_latency_ms: 0.034
        mean_latency_ms: 0.021
        min_latency_ms: 0.014
        name: one.one.one.one
        packet_count: 3
        std_dev_latency_ms: 0.011269427669584647
      properties:
        asn:
          $ref: '#/components/schemas/magic-transit_asn'
        ip:
          $ref: '#/components/schemas/magic-transit_ip'
        labels:
          $ref: '#/components/schemas/magic-transit_labels'
        max_rtt_ms:
          $ref: '#/components/schemas/magic-transit_max_rtt_ms'
        mean_rtt_ms:
          $ref: '#/components/schemas/magic-transit_mean_rtt_ms'
        min_rtt_ms:
          $ref: '#/components/schemas/magic-transit_min_rtt_ms'
        name:
          $ref: '#/components/schemas/magic-transit_name'
        packet_count:
          $ref: '#/components/schemas/magic-transit_packet_count'
        std_dev_rtt_ms:
          $ref: '#/components/schemas/magic-transit_std_dev_rtt_ms'
      type: object
    magic-transit_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    magic-transit_std_dev_rtt_ms:
      description: Standard deviation of the RTTs in ms.
      type: number
    magic-transit_packets_lost:
      description: Number of packets where no response was received.
      type: integer
    magic-transit_min_rtt_ms:
      description: Minimum RTT in ms.
      type: number
    magic-transit_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic-transit_packets_per_ttl:
      default: 3
      description: Number of packets sent at each TTL.
      maximum: 10
      minimum: 0
      type: integer
    magic-transit_targets:
      example:
      - 203.0.113.1
      - cloudflare.com
      items:
        description: Hosts as a hostname or IPv4/IPv6 address represented by strings.
        example: 203.0.113.1
        type: string
      maxLength: 10
      type: array
    magic-transit_ip:
      description: IP address of the node.
      type: string
    magic-transit_wait_time:
      default: 1
      description: Set the time (in seconds) to wait for a response to a probe.
      maximum: 5
      minimum: 1
      type: integer
    magic-transit_traceroute_time_ms:
      description: Total time of traceroute in ms.
      type: integer
    magic-transit_max_ttl:
      default: 15
      description: Max TTL.
      maximum: 64
      minimum: 0
      type: integer
    magic-transit_packet_type:
      default: icmp
      description: Type of packet sent.
      enum:
      - icmp
      - tcp
      - udp
      - gre
      - gre+icmp
      example: icmp
      type: string
    magic-transit_target_summary:
      description: Aggregated statistics from all hops about the target.
      example:
        asn: ''
        ip: 1.1.1.1
        max_latency_ms: 0.034
        mean_latency_ms: 0.021
        min_latency_ms: 0.014
        name: 1.1.1.1
        packet_count: 3
        std_dev_latency_ms: 0.011269427669584647
      type: object
    magic-transit_target:
      description: The target hostname, IPv6, or IPv6 address.
      example: 1.1.1.1
      type: string
    magic-transit_target_result:
      properties:
        colos:
          items:
            $ref: '#/components/schemas/magic-transit_colo_result'
          type: array
        target:
          $ref: '#/components/schemas/magic-transit_target'
      type: object
    magic-transit_mean_rtt_ms:
      description: Mean RTT in ms.
      type: number
    magic-transit_packet_count:
      description: Number of packets with a response from this node.
      type: integer
    magic-transit_colo_name:
      description: Source colo name.
      example: den01
      type: string
    magic-transit_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/magic-transit_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/magic-transit_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic-transit_error:
      description: Errors resulting from collecting traceroute from colo to target.
      enum:
      - ''
      - 'Could not gather traceroute data: Code 1'
      - 'Could not gather traceroute data: Code 2'
      - 'Could not gather traceroute data: Code 3'
      - 'Could not gather traceroute data: Code 4'
      example: ''
      type: string
    magic-transit_packets_sent:
      description: Number of packets sent with specified TTL.
      type: integer
    magic-transit_labels:
      description: Field appears if there is an additional annotation printed when the probe returns. Field also appears when running a GRE+ICMP traceroute to denote which traceroute a node comes from.
      items:
        type: string
      type: array
    magic-transit_colos:
      description: If no source colo names specified, all colos will be used. China colos are unavailable for traceroutes.
      example:
      - den
      - sin
      items:
        description: Source colo name.
        type: string
      type: array
    magic-transit_colo:
      properties:
        city:
          $ref: '#/components/schemas/magic-transit_colo_city'
        name:
          $ref: '#/components/schemas/magic-transit_colo_name'
      type: object
    magic-transit_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/magic-transit_messages'
        messages:
          $ref: '#/components/schemas/magic-transit_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic-transit_traceroute_response_collection:
      allOf:
      - $ref: '#/components/schemas/magic-transit_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/magic-transit_target_result'
            type: array
    magic-transit_port:
      default: 0
      description: For UDP and TCP, specifies the destination port. For ICMP, specifies the initial ICMP sequence value. Default value 0 will choose the best value to use for each protocol.
      maximum: 65535
      minimum: 0
      type: integer
    magic-transit_hop_result:
      properties:
        nodes:
          description: An array of node objects.
          items:
            $ref: '#/components/schemas/magic-transit_node_result'
          type: array
        packets_lost:
          $ref: '#/components/schemas/magic-transit_packets_lost'
        packets_sent:
          $ref: '#/components/schemas/magic-transit_packets_sent'
        packets_ttl:
          $ref: '#/components/schemas/magic-transit_packets_ttl'
      type: object
    magic-transit_name:
      description: Host name of the address, this may be the same as the IP address.
      type: string
    magic-transit_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/magic-transit_api-response-common'
      - properties:
          result:
            items: {}
            type:
            - array
            - 'null'
          result_info:
            $ref: '#/components/schemas/magic-transit_result_info'
      type: object
    magic-transit_colo_city:
      description: Source colo city.
      example: Denver, CO, US
      type: string
    magic-transit_packets_ttl:
      description: The time to live (TTL).
      type: integer
    magic-transit_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    magic-transit_max_rtt_ms:
      description: Maximum RTT in ms.
      type: number
    magic-transit_colo_result:
      properties:
        colo:
          $ref: '#/components/schemas/magic-transit_colo'
        error:
          $ref: '#/components/schemas/magic-transit_error'
        hops:
          items:
            $ref: '#/components/schemas/magic-transit_hop_result'
          type: array
        target_summary:
          $ref: '#/components/schemas/magic-transit_target_summary'
        traceroute_time_ms:
          $ref: '#/components/schemas/magic-transit_traceroute_time_ms'
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
