openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Account Load Balancer Pools API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Account Load Balancer Pools
paths:
  /accounts/{account_id}/load_balancers/pools:
    get:
      description: List configured pools.
      operationId: account-load-balancer-pools-list-pools
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      - in: query
        name: monitor
        schema:
          description: The ID of the Monitor to use for checking the health of origins within this pool.
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_schemas-response_collection'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: List Pools response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-response_collection'
          description: List Pools response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Pools
      tags:
      - Account Load Balancer Pools
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Write'
      - 'Load Balancing: Monitors and Pools Read'
    patch:
      description: Apply changes to a number of existing pools, overwriting the supplied properties. Pools are ordered by ascending `name`. Returns the list of affected pools. Supports the standard pagination query parameters, either `limit`/`offset` or `per_page`/`page`.
      operationId: account-load-balancer-pools-patch-pools
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                notification_email:
                  $ref: '#/components/schemas/load-balancing_patch_pools_notification_email'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_schemas-response_collection'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Patch Pools response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-response_collection'
          description: Patch Pools response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Patch Pools
      tags:
      - Account Load Balancer Pools
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Write'
    post:
      description: Create a new pool.
      operationId: account-load-balancer-pools-create-pool
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  $ref: '#/components/schemas/load-balancing_schemas-description'
                enabled:
                  $ref: '#/components/schemas/load-balancing_enabled'
                latitude:
                  $ref: '#/components/schemas/load-balancing_latitude'
                load_shedding:
                  $ref: '#/components/schemas/load-balancing_load_shedding'
                longitude:
                  $ref: '#/components/schemas/load-balancing_longitude'
                minimum_origins:
                  $ref: '#/components/schemas/load-balancing_minimum_origins'
                monitor:
                  $ref: '#/components/schemas/load-balancing_monitor_id'
                name:
                  $ref: '#/components/schemas/load-balancing_name'
                notification_email:
                  $ref: '#/components/schemas/load-balancing_notification_email'
                notification_filter:
                  $ref: '#/components/schemas/load-balancing_notification_filter'
                origin_steering:
                  $ref: '#/components/schemas/load-balancing_origin_steering'
                origins:
                  $ref: '#/components/schemas/load-balancing_origins'
              required:
              - origins
              - name
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_schemas-single_response'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Create Pool response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-single_response'
          description: Create Pool response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Create Pool
      tags:
      - Account Load Balancer Pools
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Write'
  /accounts/{account_id}/load_balancers/pools/{pool_id}:
    delete:
      description: Delete a configured pool.
      operationId: account-load-balancer-pools-delete-pool
      parameters:
      - in: path
        name: pool_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_schemas-id_response'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Delete Pool response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-id_response'
          description: Delete Pool response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Delete Pool
      tags:
      - Account Load Balancer Pools
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Write'
    get:
      description: Fetch a single configured pool.
      operationId: account-load-balancer-pools-pool-details
      parameters:
      - in: path
        name: pool_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_schemas-single_response'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Pool Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-single_response'
          description: Pool Details response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Pool Details
      tags:
      - Account Load Balancer Pools
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Write'
      - 'Load Balancing: Monitors and Pools Read'
    patch:
      description: Apply changes to an existing pool, overwriting the supplied properties.
      operationId: account-load-balancer-pools-patch-pool
      parameters:
      - in: path
        name: pool_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                check_regions:
                  $ref: '#/components/schemas/load-balancing_check_regions'
                description:
                  $ref: '#/components/schemas/load-balancing_schemas-description'
                disabled_at:
                  $ref: '#/components/schemas/load-balancing_schemas-disabled_at'
                enabled:
                  $ref: '#/components/schemas/load-balancing_enabled'
                latitude:
                  $ref: '#/components/schemas/load-balancing_latitude'
                load_shedding:
                  $ref: '#/components/schemas/load-balancing_load_shedding'
                longitude:
                  $ref: '#/components/schemas/load-balancing_longitude'
                minimum_origins:
                  $ref: '#/components/schemas/load-balancing_minimum_origins'
                monitor:
                  $ref: '#/components/schemas/load-balancing_monitor_id'
                name:
                  $ref: '#/components/schemas/load-balancing_name'
                notification_email:
                  $ref: '#/components/schemas/load-balancing_notification_email'
                notification_filter:
                  $ref: '#/components/schemas/load-balancing_notification_filter'
                origin_steering:
                  $ref: '#/components/schemas/load-balancing_origin_steering'
                origins:
                  $ref: '#/components/schemas/load-balancing_origins'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_schemas-single_response'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Patch Pool response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-single_response'
          description: Patch Pool response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Patch Pool
      tags:
      - Account Load Balancer Pools
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Write'
    put:
      description: Modify a configured pool.
      operationId: account-load-balancer-pools-update-pool
      parameters:
      - in: path
        name: pool_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                check_regions:
                  $ref: '#/components/schemas/load-balancing_check_regions'
                description:
                  $ref: '#/components/schemas/load-balancing_schemas-description'
                disabled_at:
                  $ref: '#/components/schemas/load-balancing_schemas-disabled_at'
                enabled:
                  $ref: '#/components/schemas/load-balancing_enabled'
                latitude:
                  $ref: '#/components/schemas/load-balancing_latitude'
                load_shedding:
                  $ref: '#/components/schemas/load-balancing_load_shedding'
                longitude:
                  $ref: '#/components/schemas/load-balancing_longitude'
                minimum_origins:
                  $ref: '#/components/schemas/load-balancing_minimum_origins'
                monitor:
                  $ref: '#/components/schemas/load-balancing_monitor_id'
                name:
                  $ref: '#/components/schemas/load-balancing_name'
                notification_email:
                  $ref: '#/components/schemas/load-balancing_notification_email'
                notification_filter:
                  $ref: '#/components/schemas/load-balancing_notification_filter'
                origin_steering:
                  $ref: '#/components/schemas/load-balancing_origin_steering'
                origins:
                  $ref: '#/components/schemas/load-balancing_origins'
              required:
              - origins
              - name
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_schemas-single_response'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Update Pool response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-single_response'
          description: Update Pool response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Update Pool
      tags:
      - Account Load Balancer Pools
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Write'
  /accounts/{account_id}/load_balancers/pools/{pool_id}/health:
    get:
      description: Fetch the latest pool health status for a single pool.
      operationId: account-load-balancer-pools-pool-health-details
      parameters:
      - in: path
        name: pool_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_health_details'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Pool Health Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_health_details'
          description: Pool Health Details response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Pool Health Details
      tags:
      - Account Load Balancer Pools
  /accounts/{account_id}/load_balancers/pools/{pool_id}/preview:
    post:
      description: Preview pool health using provided monitor details. The returned preview_id can be used in the preview endpoint to retrieve the results.
      operationId: account-load-balancer-pools-preview-pool
      parameters:
      - in: path
        name: pool_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/load-balancing_monitor-editable'
              - required:
                - expected_codes
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_preview_response'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Preview Pool response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_preview_response'
          description: Preview Pool response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Preview Pool
      tags:
      - Account Load Balancer Pools
  /accounts/{account_id}/load_balancers/pools/{pool_id}/references:
    get:
      description: Get the list of resources that reference the provided pool.
      operationId: account-load-balancer-pools-list-pool-references
      parameters:
      - in: path
        name: pool_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_schemas-references_response'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: List Pool References response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-references_response'
          description: List Pool References response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Pool References
      tags:
      - Account Load Balancer Pools
components:
  schemas:
    load-balancing_notification_filter:
      description: Filter pool and origin health notifications by resource type or health status. Use null to reset.
      example:
        origin:
          disable: true
        pool:
          healthy: false
      nullable: true
      properties:
        origin:
          $ref: '#/components/schemas/load-balancing_filter_options'
        pool:
          $ref: '#/components/schemas/load-balancing_filter_options'
      type: object
    load-balancing_schemas-name:
      description: A human-identifiable name for the origin.
      example: app-server-1
      type: string
    load-balancing_retries:
      default: 2
      description: The number of retries to attempt in case of a timeout before marking the origin as unhealthy. Retries are attempted immediately.
      type: integer
    load-balancing_schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/load-balancing_pool'
            type: array
    load-balancing_schemas-header:
      description: The request header is used to pass additional information with an HTTP request. Currently supported header is 'Host'.
      properties:
        Host:
          $ref: '#/components/schemas/load-balancing_Host'
      type: object
    load-balancing_health_details:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-single'
      - properties:
          result:
            description: A list of regions from which to run health checks. Null means every Cloudflare data center.
            example:
              pool_id: 17b5962d775c646f3f9725cbc7a53df4
              pop_health:
                Amsterdam, NL:
                  healthy: true
                  origins:
                  - 2001:DB8::5:
                      failure_reason: No failures
                      healthy: true
                      response_code: 401
                      rtt: 12.1ms
            properties:
              pool_id:
                description: Pool ID
                example: 17b5962d775c646f3f9725cbc7a53df4
                type: string
              pop_health:
                description: List of regions and associated health status.
                properties:
                  healthy:
                    description: Whether health check in region is healthy.
                    example: true
                    type: boolean
                  origins:
                    items:
                      $ref: '#/components/schemas/load-balancing_origin-health'
                    type: array
                type: object
            type: object
    load-balancing_timeout:
      default: 5
      description: The timeout (in seconds) before marking the health check as failed.
      type: integer
    load-balancing_schemas-references_response:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-collection'
      - properties:
          result:
            description: List of resources that reference a given pool.
            example:
            - reference_type: referrer
              resource_id: 699d98642c564d2e855e9661899b7252
              resource_name: www.example.com
              resource_type: load_balancer
            - reference_type: referral
              resource_id: f1aba936b94213e5b8dca0c0dbf1f9cc
              resource_name: Login page monitor
              resource_type: monitor
            items:
              properties:
                reference_type:
                  enum:
                  - '*'
                  - referral
                  - referrer
                  type: string
                resource_id:
                  type: string
                resource_name:
                  type: string
                resource_type:
                  type: string
              type: object
            type: array
    load-balancing_patch_pools_notification_email:
      description: The email address to send health status notifications to. This field is now deprecated in favor of Cloudflare Notifications for Load Balancing, so only resetting this field with an empty string `""` is accepted.
      enum:
      - ''
      example: ''
      type: string
    load-balancing_Host:
      description: The 'Host' header allows to override the hostname set in the HTTP request. Current support is 1 'Host' header override per origin.
      items:
        example: example.com
        type: string
      type: array
    load-balancing_schemas-description:
      description: A human-readable description of the pool.
      example: Primary data center - Provider XYZ
      type: string
    load-balancing_interval:
      default: 60
      description: The interval between each health check. Shorter intervals may improve failover time, but will increase load on the origins as we check from multiple locations.
      type: integer
    load-balancing_type:
      default: http
      description: The protocol to use for the health check. Currently supported protocols are 'HTTP','HTTPS', 'TCP', 'ICMP-PING', 'UDP-ICMP', and 'SMTP'.
      enum:
      - http
      - https
      - tcp
      - udp_icmp
      - icmp_ping
      - smtp
      example: https
      type: string
    load-balancing_address:
      description: The IP address (IPv4 or IPv6) of the origin, or its publicly addressable hostname. Hostnames entered here should resolve directly to the origin, and not be a hostname proxied by Cloudflare. To set an internal/reserved address, virtual_network_id must also be set.
      example: 0.0.0.0
      type: string
    load-balancing_path:
      default: /
      description: The endpoint path you want to conduct a health check against. This parameter is only valid for HTTP and HTTPS monitors.
      example: /health
      type: string
    load-balancing_networks:
      description: List of networks where Load Balancer or Pool is enabled.
      items:
        example:
        - cloudflare
        - jdcloud
        type: string
      type: array
    load-balancing_enabled:
      default: true
      description: Whether to enable (the default) or disable this pool. Disabled pools will not receive traffic and are excluded from health checks. Disabling a pool will cause any load balancers using it to failover to the next pool (if any).
      example: false
      type: boolean
    load-balancing_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      readOnly: true
      type: string
    load-balancing_description:
      description: Object description.
      example: Login page monitor
      type: string
    load-balancing_pool:
      properties:
        check_regions:
          $ref: '#/components/schemas/load-balancing_check_regions'
        created_on:
          $ref: '#/components/schemas/load-balancing_timestamp'
        description:
          $ref: '#/components/schemas/load-balancing_schemas-description'
        disabled_at:
          $ref: '#/components/schemas/load-balancing_schemas-disabled_at'
        enabled:
          $ref: '#/components/schemas/load-balancing_enabled'
        id:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
        latitude:
          $ref: '#/components/schemas/load-balancing_latitude'
        load_shedding:
          $ref: '#/components/schemas/load-balancing_load_shedding'
        longitude:
          $ref: '#/components/schemas/load-balancing_longitude'
        minimum_origins:
          $ref: '#/components/schemas/load-balancing_minimum_origins'
        modified_on:
          $ref: '#/components/schemas/load-balancing_timestamp'
        monitor:
          $ref: '#/components/schemas/load-balancing_monitor_id'
        name:
          $ref: '#/components/schemas/load-balancing_name'
        networks:
          $ref: '#/components/schemas/load-balancing_networks'
        notification_email:
          $ref: '#/components/schemas/load-balancing_notification_email'
        notification_filter:
          $ref: '#/components/schemas/load-balancing_notification_filter'
        origin_steering:
          $ref: '#/components/schemas/load-balancing_origin_steering'
        origins:
          $ref: '#/components/schemas/load-balancing_origins'
      type: object
    load-balancing_name:
      description: A short name (tag) for the pool. Only alphanumeric characters, hyphens, and underscores are allowed.
      example: primary-dc-1
      type: string
    load-balancing_origin-health:
      properties:
        ip:
          properties:
            failure_reason:
              description: Failure reason.
              example: No failure reasons
              type: string
            healthy:
              description: Origin health status.
              example: true
              type: boolean
            response_code:
              description: Response code from origin health check.
              example: 200
              type: number
            rtt:
              description: Origin RTT (Round Trip Time) response.
              example: 201.5ms
              type: string
          type: object
      type: object
    load-balancing_consecutive_down:
      default: 0
      description: To be marked unhealthy the monitored origin must fail this healthcheck N consecutive times.
      type: integer
    load-balancing_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/load-balancing_messages'
        messages:
          $ref: '#/components/schemas/load-balancing_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    load-balancing_expected_body:
      description: A case-insensitive sub-string to look for in the response body. If this string is not found, the origin will be marked as unhealthy. This parameter is only valid for HTTP and HTTPS monitors.
      example: alive
      type: string
    load-balancing_allow_insecure:
      default: false
      description: Do not validate the certificate when monitor use HTTPS. This parameter is currently only valid for HTTP and HTTPS monitors.
      example: true
      type: boolean
    load-balancing_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    load-balancing_preview_response:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-single'
      - properties:
          result:
            properties:
              pools:
                additionalProperties:
                  description: The pool name associated with the pool ID.
                  type: string
                description: Monitored pool IDs mapped to their respective names.
                example:
                  abwlnp5jbqn45ecgxd03erbgtxtqai0d: WNAM Datacenter
                  ve8h9lrcip5n5bbga9yqmdws28ay5d0l: EEU Datacenter
                type: object
              preview_id:
                $ref: '#/components/schemas/load-balancing_identifier'
            type: object
    load-balancing_expected_codes:
      default: '200'
      description: The expected HTTP response code or code range of the health check. This parameter is only valid for HTTP and HTTPS monitors.
      example: 2xx
      type: string
    load-balancing_origin_steering:
      description: Configures origin steering for the pool. Controls how origins are selected for new sessions and traffic without session affinity.
      properties:
        policy:
          default: random
          description: 'The type of origin steering policy to use.

            - `"random"`: Select an origin randomly.

            - `"hash"`: Select an origin by computing a hash over the CF-Connecting-IP address.

            - `"least_outstanding_requests"`: Select an origin by taking into consideration origin weights, as well as each origin''s number of outstanding requests. Origins with more pending requests are weighted proportionately less relative to others.

            - `"least_connections"`: Select an origin by taking into consideration origin weights, as well as each origin''s number of open connections. Origins with more open connections are weighted proportionately less relative to others. Supported for HTTP/1 and HTTP/2 connections.'
          enum:
          - random
          - hash
          - least_outstanding_requests
          - least_connections
          type: string
      type: object
    load-balancing_virtual_network_id:
      description: The virtual network subnet ID the origin belongs in. Virtual network must also belong to the account.
      example: a5624d4e-044a-4ff0-b3e1-e2465353d4b4
      type: string
    load-balancing_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    load-balancing_header:
      additionalProperties:
        items:
          type: string
        type: array
      description: The HTTP request headers to send in the health check. It is recommended you set a Host header by default. The User-Agent header cannot be overridden. This parameter is only valid for HTTP and HTTPS monitors.
      example:
        Host:
        - example.com
        X-App-ID:
        - abc123
      type: object
    load-balancing_weight:
      default: 1
      description: 'The weight of this origin relative to other origins in the pool. Based on the configured weight the total traffic is distributed among origins within the pool.

        - `origin_steering.policy="least_outstanding_requests"`: Use weight to scale the origin''s outstanding requests.

        - `origin_steering.policy="least_connections"`: Use weight to scale the origin''s open connections.'
      example: 0.6
      maximum: 1
      minimum: 0
      multipleOf: 0.01
      type: number
    load-balancing_port:
      default: 0
      description: 'The port number to connect to for the health check. Required for TCP, UDP, and SMTP checks. HTTP and HTTPS checks should only define the port when using a non-standard port (HTTP: default 80, HTTPS: default 443).'
      type: integer
    load-balancing_follow_redirects:
      default: false
      description: Follow redirects if returned by the origin. This parameter is only valid for HTTP and HTTPS monitors.
      example: true
      type: boolean
    load-balancing_longitude:
      description: The longitude of the data center containing the origins used in this pool in decimal degrees. If this is set, latitude must also be set.
      type: number
    load-balancing_schemas-disabled_at:
      description: This field shows up only if the pool is disabled. This field is set with the time the pool was disabled at.
      format: date-time
      readOnly: true
      type: string
    load-balancing_monitor_id:
      description: The ID of the Monitor to use for checking the health of origins within this pool.
      type: string
    load-balancing_check_regions:
      description: A list of regions from which to run health checks. Null means every Cloudflare data center.
      example:
      - WEU
      - ENAM
      items:
        description: 'WNAM: Western North America, ENAM: Eastern North America, WEU: Western Europe, EEU: Eastern Europe, NSAM: Northern South America, SSAM: Southern South America, OC: Oceania, ME: Middle East, NAF: North Africa, SAF: South Africa, SAS: Southern Asia, SEAS: South East Asia, NEAS: North East Asia, ALL_REGIONS: all regions (ENTERPRISE customers only).'
        enum:
        - WNAM
        - ENAM
        - WEU
        - EEU
        - NSAM
        - SSAM
        - OC
        - ME
        - NAF
        - SAF
        - SAS
        - SEAS
        - NEAS
        - ALL_REGIONS
        type: string
      nullable: true
      type: array
    load-balancing_schemas-identifier:
      example: 17b5962d775c646f3f9725cbc7a53df4
      type: string
    load-balancing_notification_email:
      description: This field is now deprecated. It has been moved to Cloudflare's Centralized Notification service https://developers.cloudflare.com/fundamentals/notifications/. The email address to send health status notifications to. This can be an individual mailbox or a mailing list. Multiple emails can be supplied as a comma delimited list.
      example: someone@example.com,sometwo@example.com
      type: string
    load-balancing_schemas-id_response:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-single'
      - properties:
          result:
            properties:
              id:
                $ref: '#/components/schemas/load-balancing_schemas-identifier'
            type: object
    load-balancing_origin:
      properties:
        address:
          $ref: '#/components/schemas/load-balancing_address'
        disabled_at:
          $ref: '#/components/schemas/load-balancing_disabled_at'
        enabled:
          $ref: '#/components/schemas/load-balancing_schemas-enabled'
        header:
          $ref: '#/components/schemas/load-balancing_schemas-header'
        name:
          $ref: '#/components/schemas/load-balancing_schemas-name'
        virtual_network_id:
          $ref: '#/components/schemas/load-balancing_virtual_network_id'
        weight:
          $ref: '#/components/schemas/load-balancing_weight'
      type: object
    load-balancing_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/load-balancing_result_info'
      type: object
    load-balancing_method:
      default: GET
      description: The method to use for the health check. This defaults to 'GET' for HTTP/HTTPS based checks and 'connection_established' for TCP based health checks.
      example: GET
      type: string
    load-balancing_latitude:
      description: The latitude of the data center containing the origins used in this pool in decimal degrees. If this is set, longitude must also be set.
      type: number
    load-balancing_load_shedding:
      description: Configures load shedding policies and percentages for the pool.
      properties:
        default_percent:
          default: 0
          description: The percent of traffic to shed from the pool, according to the default policy. Applies to new sessions and traffic without session affinity.
          maximum: 100
          minimum: 0
          type: number
        default_policy:
          default: random
          description: The default policy to use when load shedding. A random policy randomly sheds a given percent of requests. A hash policy computes a hash over the CF-Connecting-IP address and sheds all requests originating from a percent of IPs.
          enum:
          - random
          - hash
          type: string
        session_percent:
          default: 0
          description: The percent of existing sessions to shed from the pool, according to the session policy.
          maximum: 100
          minimum: 0
          type: number
        session_policy:
          default: hash
          description: Only the hash policy is supported for existing sessions (to avoid exponential decay).
          enum:
          - hash
          type: string
      type: object
    load-balancing_origins:
      description: The list of origins within this pool. Traffic directed at this pool is balanced across all currently healthy origins, provided the pool itself is healthy.
      items:
        $ref: '#/components/schemas/load-balancing_origin'
      type: array
    load-balancing_schemas-enabled:
      default: true
      description: Whether to enable (the default) this origin within the pool. Disabled origins will not receive traffic and are excluded from health checks. The origin will only be disabled for the current pool.
      example: true
      type: boolean
    load-balancing_minimum_origins:
      default: 1
      description: The minimum number of origins that must be healthy for this pool to serve traffic. If the number of healthy origins falls below this number, the pool will be marked unhealthy and will failover to the next available pool.
      type: integer
    load-balancing_schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/load-balancing_pool'
    load-balancing_identifier:
      example: f1aba936b94213e5b8dca0c0dbf1f9cc
      type: string
    load-balancing_monitor-editable:
      properties:
        allow_insecure:
          $ref: '#/components/schemas/load-balancing_allow_insecure'
        consecutive_down:
          $ref: '#/components/schemas/load-balancing_consecutive_down'
        consecutive_up:
          $ref: '#/components/schemas/load-balancing_consecutive_up'
        description:
          $ref: '#/components/schemas/load-balancing_description'
        expected_body:
          $ref: '#/components/schemas/load-balancing_expected_body'
        expected_codes:
          $ref: '#/components/schemas/load-balancing_expected_codes'
        follow_redirects:
          $ref: '#/components/schemas/load-balancing_follow_redirects'
        header:
          $ref: '#/components/schemas/load-balancing_header'
        interval:
          $ref: '#/components/schemas/load-balancing_interval'
        method:
          $ref: '#/components/schemas/load-balancing_method'
        path:
          $ref: '#/components/schemas/load-balancing_path'
        port:
          $ref: '#/components/schemas/load-balancing_port'
        probe_zone:
          $ref: '#/components/schemas/load-balancing_probe_zone'
        retries:
          $ref: '#/components/schemas/load-balancing_retries'
        timeout:
          $ref: '#/components/schemas/load-balancing_timeout'
        type:
          $ref: '#/components/schemas/load-balancing_type'
      type: object
    load-balancing_filter_options:
      description: Filter options for a particular resource type (pool or origin). Use null to reset.
      nullable: true
      properties:
        disable:
          default: false
          description: If set true, disable notifications for this type of resource (pool or origin).
          type: boolean
        healthy:
          description: If present, send notifications only for this health status (e.g. false for only DOWN events). Use null to reset (all events).
          nullable: true
          type: boolean
      type: object
    load-balancing_probe_zone:
      description: Assign this monitor to emulate the specified zone while probing. This parameter is only valid for HTTP and HTTPS monitors.
      example: example.com
      type: string
    load-balancing_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    load-balancing_disabled_at:
      description: This field shows up only if the origin is disabled. This field is set with the time the origin was disabled.
      format: date-time
      readOnly: true
      type: string
    load-balancing_api-response-single:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-common'
      - properties:
          result:
            anyOf:
            - nullable: true
              type: object
            - nullable: true
              type: string
      type: object
    load-balancing_consecutive_up:
      default: 0
      description: To be marked healthy the monitored origin must pass this healthcheck N consecutive times.
      type: integer
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
