openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Logpush Jobs for an Account API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Logpush Jobs for an Account
paths:
  /accounts/{account_id}/logpush/datasets/{dataset_id}/fields:
    get:
      description: Lists all fields available for a dataset. The response result is an object with key-value pairs, where keys are field names, and values are descriptions.
      operationId: get-accounts-account_id-logpush-datasets-dataset_id-fields
      parameters:
      - example: gateway_dns
        in: path
        name: dataset_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_dataset'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: List fields response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logpush_logpush_field_response_collection'
          description: List fields response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List fields
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      - Logs Read
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/logpush/datasets/{dataset_id}/jobs:
    get:
      description: Lists Logpush jobs for an account for a dataset.
      operationId: get-accounts-account_id-logpush-datasets-dataset_id-jobs
      parameters:
      - example: gateway_dns
        in: path
        name: dataset_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_dataset'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: List Logpush jobs for a dataset response failure
        '200':
          content:
            application/json:
              example:
                errors: []
                messages: []
                result:
                - dataset: gateway_dns
                  destination_conf: s3://mybucket/logs?region=us-west-2
                  enabled: false
                  error_message: null
                  id: 1
                  kind: ''
                  last_complete: null
                  last_error: null
                  max_upload_bytes: 5e+06
                  max_upload_interval_seconds: 30
                  max_upload_records: 1000
                  name: example.com
                  output_options:
                    CVE-2021-4428: false
                    batch_prefix: ''
                    batch_suffix: ''
                    field_delimiter: ','
                    field_names:
                    - Datetime
                    - DstIP
                    - SrcIP
                    output_type: ndjson
                    record_delimiter: ''
                    record_prefix: '{'
                    record_suffix: '}

                      '
                    record_template: ''
                    sample_rate: 1
                    timestamp_format: unixnano
                success: true
              schema:
                $ref: '#/components/schemas/logpush_logpush_job_response_collection'
          description: List Logpush jobs for a dataset response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Logpush jobs for a dataset
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      - Logs Read
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/logpush/jobs:
    get:
      description: Lists Logpush jobs for an account.
      operationId: get-accounts-account_id-logpush-jobs
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: List Logpush jobs response failure
        '200':
          content:
            application/json:
              example:
                errors: []
                messages: []
                result:
                - dataset: gateway_dns
                  destination_conf: s3://mybucket/logs?region=us-west-2
                  enabled: false
                  error_message: null
                  id: 1
                  kind: ''
                  last_complete: null
                  last_error: null
                  max_upload_bytes: 5e+06
                  max_upload_interval_seconds: 30
                  max_upload_records: 1000
                  name: example.com
                  output_options:
                    CVE-2021-4428: false
                    batch_prefix: ''
                    batch_suffix: ''
                    field_delimiter: ','
                    field_names:
                    - Datetime
                    - DstIP
                    - SrcIP
                    output_type: ndjson
                    record_delimiter: ''
                    record_prefix: '{'
                    record_suffix: '}

                      '
                    record_template: ''
                    sample_rate: 1
                    timestamp_format: unixnano
                success: true
              schema:
                $ref: '#/components/schemas/logpush_logpush_job_response_collection'
          description: List Logpush jobs response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Logpush jobs
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      - Logs Read
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Creates a new Logpush job for an account.
      operationId: post-accounts-account_id-logpush-jobs
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      requestBody:
        content:
          application/json:
            example:
              dataset: gateway_dns
              destination_conf: s3://mybucket/logs?region=us-west-2
              enabled: false
              kind: ''
              max_upload_bytes: 5e+06
              max_upload_interval_seconds: 30
              max_upload_records: 1000
              name: example.com
              output_options:
                CVE-2021-4428: false
                batch_prefix: ''
                batch_suffix: ''
                field_delimiter: ','
                field_names:
                - Datetime
                - DstIP
                - SrcIP
                output_type: ndjson
                record_delimiter: ''
                record_prefix: '{'
                record_suffix: '}

                  '
                record_template: ''
                sample_rate: 1
                timestamp_format: unixnano
              ownership_challenge": '00000000000000000000'
            schema:
              properties:
                dataset:
                  $ref: '#/components/schemas/logpush_dataset'
                destination_conf:
                  $ref: '#/components/schemas/logpush_destination_conf'
                enabled:
                  $ref: '#/components/schemas/logpush_enabled'
                frequency:
                  $ref: '#/components/schemas/logpush_frequency'
                kind:
                  $ref: '#/components/schemas/logpush_kind'
                logpull_options:
                  $ref: '#/components/schemas/logpush_logpull_options'
                max_upload_bytes:
                  $ref: '#/components/schemas/logpush_max_upload_bytes'
                max_upload_interval_seconds:
                  $ref: '#/components/schemas/logpush_max_upload_interval_seconds'
                max_upload_records:
                  $ref: '#/components/schemas/logpush_max_upload_records'
                name:
                  $ref: '#/components/schemas/logpush_name'
                output_options:
                  $ref: '#/components/schemas/logpush_output_options'
                ownership_challenge:
                  $ref: '#/components/schemas/logpush_ownership_challenge'
              required:
              - destination_conf
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: Create Logpush job response failure
        '200':
          content:
            application/json:
              example:
                errors: []
                messages: []
                result:
                  dataset: gateway_dns
                  destination_conf: s3://mybucket/logs?region=us-west-2
                  enabled: false
                  error_message: null
                  id: 1
                  kind: ''
                  last_complete: null
                  last_error: null
                  max_upload_bytes: 5e+06
                  max_upload_interval_seconds: 30
                  max_upload_records: 1000
                  name: example.com
                  output_options:
                    CVE-2021-4428: false
                    batch_prefix: ''
                    batch_suffix: ''
                    field_delimiter: ','
                    field_names:
                    - Datetime
                    - DstIP
                    - SrcIP
                    output_type: ndjson
                    record_delimiter: ''
                    record_prefix: '{'
                    record_suffix: '}

                      '
                    record_template: ''
                    sample_rate: 1
                    timestamp_format: unixnano
                success: true
              schema:
                $ref: '#/components/schemas/logpush_logpush_job_response_single'
          description: Create Logpush job response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Create Logpush job
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/logpush/jobs/{job_id}:
    delete:
      description: Deletes a Logpush job.
      operationId: delete-accounts-account_id-logpush-jobs-job_id
      parameters:
      - in: path
        name: job_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_id'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: Delete Logpush job response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common'
                - properties:
                    result:
                      properties:
                        id:
                          $ref: '#/components/schemas/logpush_id'
                      type: object
          description: Delete Logpush job response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Delete Logpush job
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    get:
      description: Gets the details of a Logpush job.
      operationId: get-accounts-account_id-logpush-jobs-job_id
      parameters:
      - in: path
        name: job_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_id'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: Get Logpush job details response failure
        '200':
          content:
            application/json:
              example:
                errors: []
                messages: []
                result:
                  dataset: gateway_dns
                  destination_conf: s3://mybucket/logs?region=us-west-2
                  enabled: false
                  error_message: null
                  id: 1
                  kind: ''
                  last_complete: null
                  last_error: null
                  max_upload_bytes: 5e+06
                  max_upload_interval_seconds: 30
                  max_upload_records: 1000
                  name: example.com
                  output_options:
                    CVE-2021-4428: false
                    batch_prefix: ''
                    batch_suffix: ''
                    field_delimiter: ','
                    field_names:
                    - Datetime
                    - DstIP
                    - SrcIP
                    output_type: ndjson
                    record_delimiter: ''
                    record_prefix: '{'
                    record_suffix: '}

                      '
                    record_template: ''
                    sample_rate: 1
                    timestamp_format: unixnano
                success: true
              schema:
                $ref: '#/components/schemas/logpush_logpush_job_response_single'
          description: Get Logpush job details response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get Logpush job details
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      - Logs Read
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Updates a Logpush job.
      operationId: put-accounts-account_id-logpush-jobs-job_id
      parameters:
      - in: path
        name: job_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_id'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      requestBody:
        content:
          application/json:
            example:
              destination_conf: s3://mybucket/logs?region=us-west-2
              enabled: false
              kind: ''
              max_upload_bytes: 5e+06
              max_upload_interval_seconds: 30
              max_upload_records: 1000
              output_options:
                CVE-2021-4428: false
                batch_prefix: ''
                batch_suffix: ''
                field_delimiter: ','
                field_names:
                - Datetime
                - DstIP
                - SrcIP
                output_type: ndjson
                record_delimiter: ''
                record_prefix: '{'
                record_suffix: '}

                  '
                record_template: ''
                sample_rate: 1
                timestamp_format: unixnano
              ownership_challenge": '00000000000000000000'
            schema:
              properties:
                destination_conf:
                  $ref: '#/components/schemas/logpush_destination_conf'
                enabled:
                  $ref: '#/components/schemas/logpush_enabled'
                frequency:
                  $ref: '#/components/schemas/logpush_frequency'
                kind:
                  $ref: '#/components/schemas/logpush_kind'
                logpull_options:
                  $ref: '#/components/schemas/logpush_logpull_options'
                max_upload_bytes:
                  $ref: '#/components/schemas/logpush_max_upload_bytes'
                max_upload_interval_seconds:
                  $ref: '#/components/schemas/logpush_max_upload_interval_seconds'
                max_upload_records:
                  $ref: '#/components/schemas/logpush_max_upload_records'
                output_options:
                  $ref: '#/components/schemas/logpush_output_options'
                ownership_challenge:
                  $ref: '#/components/schemas/logpush_ownership_challenge'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: Update Logpush job response failure
        '200':
          content:
            application/json:
              example:
                errors: []
                messages: []
                result:
                  dataset: gateway_dns
                  destination_conf: s3://mybucket/logs?region=us-west-2
                  enabled: false
                  error_message: null
                  id: 1
                  kind: ''
                  last_complete: null
                  last_error: null
                  max_upload_bytes: 5e+06
                  max_upload_interval_seconds: 30
                  max_upload_records: 1000
                  name: example.com
                  output_options:
                    CVE-2021-4428: false
                    batch_prefix: ''
                    batch_suffix: ''
                    field_delimiter: ','
                    field_names:
                    - Datetime
                    - DstIP
                    - SrcIP
                    output_type: ndjson
                    record_delimiter: ''
                    record_prefix: '{'
                    record_suffix: '}

                      '
                    record_template: ''
                    sample_rate: 1
                    timestamp_format: unixnano
                success: true
              schema:
                $ref: '#/components/schemas/logpush_logpush_job_response_single'
          description: Update Logpush job response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Update Logpush job
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/logpush/ownership:
    post:
      description: Gets a new ownership challenge sent to your destination.
      operationId: post-accounts-account_id-logpush-ownership
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                destination_conf:
                  $ref: '#/components/schemas/logpush_destination_conf'
              required:
              - destination_conf
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: Get ownership challenge response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logpush_get_ownership_response'
          description: Get ownership challenge response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get ownership challenge
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/logpush/ownership/validate:
    post:
      description: Validates ownership challenge of the destination.
      operationId: post-accounts-account_id-logpush-ownership-validate
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                destination_conf:
                  $ref: '#/components/schemas/logpush_destination_conf'
                ownership_challenge:
                  $ref: '#/components/schemas/logpush_ownership_challenge'
              required:
              - destination_conf
              - ownership_challenge
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: Validate ownership challenge response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logpush_validate_ownership_response'
          description: Validate ownership challenge response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Validate ownership challenge
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/logpush/validate/destination/exists:
    post:
      description: Checks if there is an existing job with a destination.
      operationId: delete-accounts-account_id-logpush-validate-destination-exists
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                destination_conf:
                  $ref: '#/components/schemas/logpush_destination_conf'
              required:
              - destination_conf
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: Check destination exists response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logpush_destination_exists_response'
          description: Check destination exists response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Check destination exists
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/logpush/validate/origin:
    post:
      description: Validates logpull origin with logpull_options.
      operationId: post-accounts-account_id-logpush-validate-origin
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/logpush_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                logpull_options:
                  $ref: '#/components/schemas/logpush_logpull_options'
              required:
              - logpull_options
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/logpush_api-response-common-failure'
          description: Validate origin response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logpush_validate_response'
          description: Validate origin response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Validate origin
      tags:
      - Logpush Jobs for an Account
      x-api-token-group:
      - Logs Write
      x-cfPermissionsRequired:
        enum:
        - '#logs:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    logpush_logpush_job:
      nullable: true
      properties:
        dataset:
          $ref: '#/components/schemas/logpush_dataset'
        destination_conf:
          $ref: '#/components/schemas/logpush_destination_conf'
        enabled:
          $ref: '#/components/schemas/logpush_enabled'
        error_message:
          $ref: '#/components/schemas/logpush_error_message'
        frequency:
          $ref: '#/components/schemas/logpush_frequency'
        id:
          $ref: '#/components/schemas/logpush_id'
        kind:
          $ref: '#/components/schemas/logpush_kind'
        last_complete:
          $ref: '#/components/schemas/logpush_last_complete'
        last_error:
          $ref: '#/components/schemas/logpush_last_error'
        logpull_options:
          $ref: '#/components/schemas/logpush_logpull_options'
        max_upload_bytes:
          $ref: '#/components/schemas/logpush_max_upload_bytes'
        max_upload_interval_seconds:
          $ref: '#/components/schemas/logpush_max_upload_interval_seconds'
        max_upload_records:
          $ref: '#/components/schemas/logpush_max_upload_records'
        name:
          $ref: '#/components/schemas/logpush_name'
        output_options:
          $ref: '#/components/schemas/logpush_output_options'
      type: object
    logpush_logpush_field_response_collection:
      allOf:
      - $ref: '#/components/schemas/logpush_api-response-common'
      - properties:
          result:
            items:
              nullable: true
              properties:
                key:
                  example: value
                  type: string
              type: object
            type: object
    logpush_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    logpush_get_ownership_response:
      allOf:
      - $ref: '#/components/schemas/logpush_api-response-common'
      - properties:
          result:
            nullable: true
            properties:
              filename:
                example: logs/challenge-filename.txt
                type: string
              message:
                example: ''
                type: string
              valid:
                example: true
                type: boolean
            type: object
    logpush_output_options:
      description: The structured replacement for `logpull_options`. When including this field, the `logpull_option` field will be ignored.
      nullable: true
      properties:
        CVE-2021-4428:
          default: false
          description: If set to true, will cause all occurrences of `${` in the generated files to be replaced with `x{`.
          nullable: true
          type: boolean
        batch_prefix:
          default: ''
          description: String to be prepended before each batch.
          nullable: true
          type: string
        batch_suffix:
          default: ''
          description: String to be appended after each batch.
          nullable: true
          type: string
        field_delimiter:
          default: ','
          description: String to join fields. This field be ignored when `record_template` is set.
          nullable: true
          type: string
        field_names:
          description: List of field names to be included in the Logpush output. For the moment, there is no option to add all fields at once, so you must specify all the fields names you are interested in.
          example:
          - ClientIP
          - EdgeStartTimestamp
          - RayID
          items:
            type: string
          type: array
        output_type:
          default: ndjson
          description: Specifies the output type, such as `ndjson` or `csv`. This sets default values for the rest of the settings, depending on the chosen output type. Some formatting rules, like string quoting, are different between output types.
          enum:
          - ndjson
          - csv
          example: ndjson
          type: string
        record_delimiter:
          default: ''
          description: String to be inserted in-between the records as separator.
          nullable: true
          type: string
        record_prefix:
          default: '{'
          description: String to be prepended before each record.
          nullable: true
          type: string
        record_suffix:
          default: '}

            '
          description: String to be appended after each record.
          nullable: true
          type: string
        record_template:
          default: ''
          description: String to use as template for each record instead of the default comma-separated list. All fields used in the template must be present in `field_names` as well, otherwise they will end up as null. Format as a Go `text/template` without any standard functions, like conditionals, loops, sub-templates, etc.
          nullable: true
          type: string
        sample_rate:
          default: 1
          description: Floating number to specify sampling rate. Sampling is applied on top of filtering, and regardless of the current `sample_interval` of the data.
          format: float
          maximum: 1
          minimum: 0
          nullable: true
          type: number
        timestamp_format:
          default: unixnano
          description: String to specify the format for timestamps, such as `unixnano`, `unix`, or `rfc3339`.
          enum:
          - unixnano
          - unix
          - rfc3339
          type: string
      type: object
    logpush_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/logpush_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/logpush_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    logpush_validate_response:
      allOf:
      - $ref: '#/components/schemas/logpush_api-response-common'
      - properties:
          result:
            nullable: true
            properties:
              message:
                example: ''
                type: string
              valid:
                example: true
                type: boolean
            type: object
    logpush_logpush_job_response_collection:
      allOf:
      - $ref: '#/components/schemas/logpush_api-response-common'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/logpush_logpush_job'
            type: array
    logpush_destination_exists_response:
      allOf:
      - $ref: '#/components/schemas/logpush_api-response-common'
      - properties:
          result:
            nullable: true
            properties:
              exists:
                example: false
                type: boolean
            type: object
    logpush_validate_ownership_response:
      allOf:
      - $ref: '#/components/schemas/logpush_api-response-common'
      - properties:
          result:
            nullable: true
            properties:
              valid:
                example: true
                type: boolean
            type: object
    logpush_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    logpush_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/logpush_messages'
        messages:
          $ref: '#/components/schemas/logpush_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    logpush_logpush_job_response_single:
      allOf:
      - $ref: '#/components/schemas/logpush_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/logpush_logpush_job'
    logpush_max_upload_records:
      default: 100000
      description: The maximum number of log lines per batch. This setting must be between 1000 and 1,000,000 lines, or `0` to disable it. Note that you cannot specify a minimum number of log lines per batch; this means that log files may contain many fewer lines than this. This parameter is not available for jobs with `edge` as its kind.
      example: 1000
      maximum: 1e+06
      minimum: 1000
      nullable: true
      type: integer
    logpush_ownership_challenge:
      description: Ownership challenge token to prove destination ownership.
      example: '00000000000000000000'
      maxLength: 4096
      pattern: ^[a-zA-Z0-9/\+\.\-_]*$
      type: string
    logpush_id:
      description: Unique id of the job.
      minimum: 1
      type: integer
    logpush_name:
      description: Optional human readable job name. Not unique. Cloudflare suggests that you set this to a meaningful string, like the domain name, to make it easier to identify your job.
      example: example.com
      maxLength: 512
      nullable: true
      pattern: ^[a-zA-Z0-9\-\.]*$
      type: string
    logpush_last_error:
      description: Records the last time the job failed. If not null, the job is currently failing. If null, the job has either never failed or has run successfully at least once since last failure. See also the error_message field.
      format: date-time
      nullable: true
      type: string
    logpush_frequency:
      default: high
      deprecated: true
      description: This field is deprecated. Please use `max_upload_*` parameters instead. The frequency at which Cloudflare sends batches of logs to your destination. Setting frequency to high sends your logs in larger quantities of smaller files. Setting frequency to low sends logs in smaller quantities of larger files.
      enum:
      - high
      - low
      example: high
      nullable: true
      type: string
    logpush_max_upload_bytes:
      description: The maximum uncompressed file size of a batch of logs. This setting value must be between `5 MB` and `1 GB`, or `0` to disable it. Note that you cannot set a minimum file size; this means that log files may be much smaller than this batch size. This parameter is not available for jobs with `edge` as its kind.
      example: 5e+06
      maximum: 1e+09
      minimum: 5e+06
      nullable: true
      type: integer
    logpush_api-response-single:
      allOf:
      - $ref: '#/components/schemas/logpush_api-response-common'
      type: object
    logpush_destination_conf:
      description: Uniquely identifies a resource (such as an s3 bucket) where data will be pushed. Additional configuration parameters supported by the destination may be included.
      example: s3://mybucket/logs?region=us-west-2
      format: uri
      maxLength: 4096
      type: string
    logpush_kind:
      default: ''
      description: The kind parameter (optional) is used to differentiate between Logpush and Edge Log Delivery jobs. Currently, Edge Log Delivery is only supported for the `http_requests` dataset.
      enum:
      - edge
      example: ''
      nullable: true
      type: string
    logpush_dataset:
      description: Name of the dataset. A list of supported datasets can be found on the [Developer Docs](https://developers.cloudflare.com/logs/reference/log-fields/).
      example: http_requests
      maxLength: 256
      nullable: true
      pattern: ^[a-zA-Z0-9_\-]*$
      type: string
    logpush_logpull_options:
      deprecated: true
      description: This field is deprecated. Use `output_options` instead. Configuration string. It specifies things like requested fields and timestamp formats. If migrating from the logpull api, copy the url (full url or just the query string) of your call here, and logpush will keep on making this call for you, setting start and end times appropriately.
      example: fields=RayID,ClientIP,EdgeStartTimestamp&timestamps=rfc3339
      format: uri-reference
      maxLength: 4096
      nullable: true
      type: string
    logpush_error_message:
      description: 'If not null, the job is currently failing. Failures are usually repetitive (example: no permissions to write to destination bucket). Only the last failure is recorded. On successful execution of a job the error_message and last_error are set to null.'
      format: date-time
      nullable: true
      type: string
    logpush_max_upload_interval_seconds:
      default: 30
      description: The maximum interval in seconds for log batches. This setting must be between 30 and 300 seconds (5 minutes), or `0` to disable it. Note that you cannot specify a minimum interval for log batches; this means that log files may be sent in shorter intervals than this. This parameter is only used for jobs with `edge` as its kind.
      example: 30
      maximum: 300
      minimum: 30
      nullable: true
      type: integer
    logpush_enabled:
      description: Flag that indicates if the job is enabled.
      example: false
      type: boolean
    logpush_last_complete:
      description: Records the last time for which logs have been successfully pushed. If the last successful push was for logs range 2018-07-23T10:00:00Z to 2018-07-23T10:01:00Z then the value of this field will be 2018-07-23T10:01:00Z. If the job has never run or has just been enabled and hasn't run yet then the field will be empty.
      format: date-time
      nullable: true
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
