openapi: 3.2.0
info:
  title: Postman Comments API
  description: The Postman API enables you to programmatically access data stored in your Postman account.
  version: '1.0'
  termsOfService: https://www.postman.com/legal/terms/
  contact:
    name: Postman Support
    email: help@postman.com
    url: https://www.postman.com/community/
servers:
- url: https://api.getpostman.com
- url: https://api.eu.postman.com
security:
- PostmanApiKey: []
- scimApiKey: []
tags:
- name: Comments
  description: The **Comments** endpoints enable you to manage comments on an API element. You can use comments to collaborate and discuss your work with your teammates in Postman.
paths:
  /apis/{apiId}/comments:
    parameters:
    - $ref: '#/components/parameters/apiId'
    get:
      summary: APIs.io Engineering Platform Get an API's comments
      description: Gets all comments left by users in an API.
      operationId: getApiComments
      tags:
      - Comments
      responses:
        '200':
          $ref: '#/components/responses/commentGet'
        '400':
          $ref: '#/components/responses/v10HeaderMissing'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403ErrorAndFeatureUnavailable'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    post:
      summary: APIs.io Engineering Platform Create an API comment
      description: 'Creates a comment on an API.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      tags:
      - Comments
      operationId: createApiComment
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '201':
          $ref: '#/components/responses/commentCreated'
        '400':
          $ref: '#/components/responses/v10HeaderMissing'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403ErrorAndFeatureUnavailable'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /apis/{apiId}/comments/{commentId}:
    parameters:
    - $ref: '#/components/parameters/apiId'
    - $ref: '#/components/parameters/commentId'
    put:
      summary: APIs.io Engineering Platform Update an API's comment
      description: 'Updates a comment on an API.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      operationId: updateApiComment
      tags:
      - Comments
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '200':
          $ref: '#/components/responses/commentUpdated'
        '400':
          $ref: '#/components/responses/v10HeaderMissing'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403ErrorAndFeatureUnavailable'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    delete:
      summary: APIs.io Engineering Platform Delete an API's comment
      description: 'Deletes a comment from an API. On success, this returns an HTTP `204 No Content` response.


        **Note:**


        Deleting the first comment of a thread deletes all the comments in the thread.'
      operationId: deleteApiComment
      tags:
      - Comments
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/v10HeaderMissing'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403ErrorAndFeatureUnavailable'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /collections/{collectionId}/comments:
    parameters:
    - $ref: '#/components/parameters/collectionUid'
    get:
      summary: APIs.io Engineering Platform Get a collection's comments
      description: Gets all comments left by users in a collection.
      operationId: getCollectionComments
      tags:
      - Comments
      responses:
        '200':
          $ref: '#/components/responses/commentGet'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    post:
      summary: APIs.io Engineering Platform Create a collection comment
      description: 'Creates a comment on a collection.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      tags:
      - Comments
      operationId: createCollectionComment
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '201':
          $ref: '#/components/responses/commentCreated'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /collections/{collectionId}/comments/{commentId}:
    parameters:
    - $ref: '#/components/parameters/collectionUid'
    - $ref: '#/components/parameters/commentId'
    put:
      summary: APIs.io Engineering Platform Update a collection's comment
      description: 'Updates a comment on a collection.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      operationId: updateCollectionComment
      tags:
      - Comments
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '200':
          $ref: '#/components/responses/commentUpdated'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    delete:
      summary: APIs.io Engineering Platform Delete a collection's comment
      description: 'Deletes a comment from a collection. On success, this returns an HTTP `204 No Content` response.


        **Note:**


        Deleting the first comment of a thread deletes all the comments in the thread.'
      operationId: deleteCollectionComment
      tags:
      - Comments
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /collections/{collectionId}/folders/{folderId}/comments:
    parameters:
    - $ref: '#/components/parameters/collectionUid'
    - $ref: '#/components/parameters/collectionFolderUid'
    get:
      summary: APIs.io Engineering Platform Get a folder's comments
      description: Gets all comments left by users in a folder.
      operationId: getFolderComments
      tags:
      - Comments
      responses:
        '200':
          $ref: '#/components/responses/commentGet'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    post:
      summary: APIs.io Engineering Platform Create a folder comment
      description: 'Creates a comment on a folder.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      tags:
      - Comments
      operationId: createFolderComment
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '201':
          $ref: '#/components/responses/commentCreated'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /collections/{collectionId}/folders/{folderId}/comments/{commentId}:
    parameters:
    - $ref: '#/components/parameters/collectionUid'
    - $ref: '#/components/parameters/collectionFolderUid'
    - $ref: '#/components/parameters/commentId'
    put:
      summary: APIs.io Engineering Platform Update a folder's comment
      description: 'Updates a comment on a folder.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      operationId: updateFolderComment
      tags:
      - Comments
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '200':
          $ref: '#/components/responses/commentUpdated'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    delete:
      summary: APIs.io Engineering Platform Delete a folder's comment
      description: 'Deletes a comment from a folder. On success, this returns an HTTP `204 No Content` response.


        **Note:**


        Deleting the first comment of a thread deletes all the comments in the thread.'
      operationId: deleteFolderComment
      tags:
      - Comments
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /collections/{collectionId}/requests/{requestId}/comments:
    parameters:
    - $ref: '#/components/parameters/collectionUid'
    - $ref: '#/components/parameters/collectionRequestUid'
    get:
      summary: APIs.io Engineering Platform Get a request's comments
      description: Gets all comments left by users in a request.
      operationId: getRequestComments
      tags:
      - Comments
      responses:
        '200':
          $ref: '#/components/responses/commentGet'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    post:
      summary: APIs.io Engineering Platform Create a request comment
      description: 'Creates a comment on a request.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      tags:
      - Comments
      operationId: createRequestComment
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '201':
          $ref: '#/components/responses/commentCreated'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /collections/{collectionId}/requests/{requestId}/comments/{commentId}:
    parameters:
    - $ref: '#/components/parameters/collectionUid'
    - $ref: '#/components/parameters/collectionRequestUid'
    - $ref: '#/components/parameters/commentId'
    put:
      summary: APIs.io Engineering Platform Update a request's comment
      description: 'Updates a comment on a request.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      operationId: updateRequestComment
      tags:
      - Comments
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '200':
          $ref: '#/components/responses/commentUpdated'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    delete:
      summary: APIs.io Engineering Platform Delete a request's comment
      description: 'Deletes a comment from a request. On success, this returns an HTTP `204 No Content` response.


        **Note:**


        Deleting the first comment of a thread deletes all the comments in the thread.'
      operationId: deleteRequestComment
      tags:
      - Comments
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /collections/{collectionId}/responses/{responseId}/comments:
    parameters:
    - $ref: '#/components/parameters/collectionUid'
    - $ref: '#/components/parameters/collectionResponseUid'
    get:
      summary: APIs.io Engineering Platform Get a response's comments
      description: Gets all comments left by users in a response.
      operationId: getResponseComments
      tags:
      - Comments
      responses:
        '200':
          $ref: '#/components/responses/commentGet'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    post:
      summary: APIs.io Engineering Platform Create a response comment
      description: 'Creates a comment on a response.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      tags:
      - Comments
      operationId: createResponseComment
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '201':
          $ref: '#/components/responses/commentCreated'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /collections/{collectionId}/responses/{responseId}/comments/{commentId}:
    parameters:
    - $ref: '#/components/parameters/collectionUid'
    - $ref: '#/components/parameters/collectionResponseUid'
    - $ref: '#/components/parameters/commentId'
    put:
      summary: APIs.io Engineering Platform Update a response's comment
      description: 'Updates a comment on a response.


        **Note:**


        This endpoint accepts a max of 10,000 characters.'
      operationId: updateResponseComment
      tags:
      - Comments
      requestBody:
        $ref: '#/components/requestBodies/commentCreateUpdate'
      responses:
        '200':
          $ref: '#/components/responses/commentUpdated'
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
    delete:
      summary: APIs.io Engineering Platform Delete a response's comment
      description: 'Deletes a comment from a response. On success, this returns an HTTP `204 No Content` response.


        **Note:**


        Deleting the first comment of a thread deletes all the comments in the thread.'
      operationId: deleteResponseComment
      tags:
      - Comments
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/comment401Error'
        '403':
          $ref: '#/components/responses/comment403Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
  /comments-resolutions/{threadId}:
    post:
      summary: APIs.io Engineering Platform Resolve a comment thread
      description: 'Resolves a comment and any associated replies. On success, this returns an HTTP `204 No Content` response.


        Comment thread IDs return in the GET comments response for APIs, collections, and collection items.'
      operationId: resolveCommentThread
      tags:
      - Comments
      responses:
        '204':
          description: Successful Response
        '401':
          $ref: '#/components/responses/comment401Error'
        '404':
          $ref: '#/components/responses/comment404Error'
        '500':
          $ref: '#/components/responses/comment500Error'
      parameters:
      - $ref: '#/components/parameters/threadId'
components:
  examples:
    v10HeaderMissing:
      value:
        name: instanceNotFoundError
        message: API not found. For v10 and later APIs, ensure that your request sends the "application/vnd.api.v10+json" Accept header.
    featureUnavailable403Error:
      value:
        type: https://api.postman.com/problems/forbidden
        title: Forbidden
        detail: This feature isn't available in your region.
        status: 403
    comment403Error:
      value:
        type: https://api.postman.com/problems/forbidden
        title: Forbidden
        detail: Forbidden
        status: 403
  responses:
    commentGet:
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/commentResponse'
          example:
            data:
            - id: 46818
              threadId: 12345
              createdBy: 12345678
              createdAt: '2024-01-18T12:00:54.000Z'
              updatedAt: '2024-01-18T12:00:54.000Z'
              body: This is also an example.
            - id: 46817
              threadId: 67890
              createdBy: 87654321
              createdAt: '2024-01-18T11:48:01.000Z'
              updatedAt: '2024-01-18T11:48:01.000Z'
              body: Another example.
            - id: 46814
              threadId: 23456
              createdBy: 12345678
              createdAt: '2024-01-18T11:30:40.000Z'
              updatedAt: '2024-01-18T11:30:40.000Z'
              body: This is an example.
    comment403Error:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/comment403Error'
          example:
            type: https://api.postman.com/problems/forbidden
            title: Forbidden
            detail: Forbidden
            status: 403
    commentUpdated:
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/commentCreatedUpdated'
          example:
            data:
              id: 46814
              threadId: 12345
              createdBy: 12345678
              createdAt: '2024-01-18T11:30:40.000Z'
              updatedAt: '2024-01-18T11:30:40.000Z'
              body: This is an updated example.
    comment500Error:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/internal-server-error
              title:
                type: string
                description: A short summary of the problem.
                example: Internal Server Error
              detail:
                type: string
                description: Information about the error.
                example: Internal Server Error
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 500
          example:
            type: https://api.postman.com/problems/internal-server-error
            title: Internal Server Error
            detail: Internal Server Error
            status: 500
    comment401Error:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/unauthorized
              title:
                type: string
                description: A short summary of the problem.
                example: Unauthorized
              detail:
                type: string
                description: Information about the error.
                example: Unauthorized
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 401
          example:
            type: https://api.postman.com/problems/unauthorized
            title: Unauthorized
            detail: Unauthorized
            status: 401
    v10HeaderMissing:
      description: Missing v10 Accept Header
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/v10HeaderMissing'
          examples:
            Missing v10 Accept Header:
              $ref: '#/components/examples/v10HeaderMissing'
    comment403ErrorAndFeatureUnavailable:
      description: Forbidden
      content:
        application/json:
          schema:
            anyOf:
            - $ref: '#/components/schemas/comment403Error'
            - $ref: '#/components/schemas/featureUnavailable403Error'
          examples:
            Forbidden:
              $ref: '#/components/examples/comment403Error'
            Feature Unavailable:
              $ref: '#/components/examples/featureUnavailable403Error'
    commentCreated:
      description: Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/commentCreatedUpdated'
          example:
            data:
              id: 46814
              createdBy: 12345678
              createdAt: '2024-01-18T11:30:40.000Z'
              updatedAt: '2024-01-18T11:30:40.000Z'
              body: This is an example.
    comment404Error:
      description: Not Found
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/not-found
              title:
                type: string
                description: A short summary of the problem.
                example: Not Found
              detail:
                type: string
                description: Information about the error.
                example: Not Found
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 404
          example:
            type: https://api.postman.com/problems/not-found
            title: Not Found
            detail: Not Found
            status: 404
  schemas:
    featureUnavailable403Error:
      title: Feature Unavailable
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/forbidden
        title:
          type: string
          description: A short summary of the problem.
          example: Forbidden
        detail:
          type: string
          description: Information about the error.
          example: This feature isn't available in your region.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 403
    commentCreateUpdate:
      title: Comment Payload Object
      type: object
      description: Information about the comment.
      required:
      - body
      properties:
        body:
          type: string
          description: The contents of the comment.
          example: This is an example.
        tags:
          type: object
          description: Information about users tagged in the `body` comment.
          properties:
            userName:
              type: object
              required:
              - type
              - id
              description: An object that contains information about the tagged user. The object's name is the user's Postman username. For example, `@user-postman`.
              properties:
                type:
                  type: string
                  description: The `user` value.
                  enum:
                  - user
                  example: user
                id:
                  type: integer
                  description: The user's ID.
                  example: 87654321
    commentResponse:
      title: Comment Response Object
      type: object
      properties:
        data:
          type: array
          required:
          - id
          - threadId
          - createdBy
          - createdAt
          - updatedAt
          - body
          items:
            type: object
            description: Information about the comment.
            properties:
              id:
                type: integer
                description: The comment's ID.
                example: 46814
              threadId:
                type: integer
                description: The comment's thread ID.
                example: 12345
              createdBy:
                type: integer
                description: The user ID of the user who created the comment.
                example: 12345678
              createdAt:
                type: string
                format: date-time
                description: The date and time at which the comment was created.
                example: '2024-01-18T11:30:40.000Z'
              updatedAt:
                type: string
                format: date-time
                description: The date and time when the comment was last updated.
                example: '2024-01-18T11:30:40.000Z'
              body:
                type: string
                description: The contents of the comment.
                example: This is an example.
    comment403Error:
      title: Forbidden
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/forbidden
        title:
          type: string
          description: A short summary of the problem.
          example: Forbidden
        detail:
          type: string
          description: Information about the error.
          example: Forbidden
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 403
    v10HeaderMissing:
      title: Missing v10 Accept Header
      type: object
      properties:
        name:
          type: string
          description: The error name.
          example: instanceNotFoundError
        message:
          type: string
          description: The error message.
          example: API not found. For v10 and later APIs, ensure that your request sends the "application/vnd.api.v10+json" Accept header.
    commentCreatedUpdated:
      title: Comment Updated/Created Object
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: integer
              description: The comment's ID.
              example: 46814
            threadId:
              type: integer
              description: The comment's thread ID.
              example: 12345
            createdBy:
              type: integer
              description: The user ID of the user who created the comment.
              example: 12345678
            createdAt:
              type: string
              format: date-time
              description: The date and time at which the comment was created.
              example: '2024-01-18T11:30:40.000Z'
            updatedAt:
              type: string
              format: date-time
              description: The date and time when the comment was last updated.
              example: '2024-01-18T11:30:40.000Z'
            body:
              type: string
              description: The contents of the comment.
              example: This is an example.
  parameters:
    commentId:
      name: commentId
      in: path
      required: true
      description: The comment's ID.
      schema:
        type: integer
        example: 46814
    threadId:
      name: threadId
      in: path
      required: true
      description: The comment's thread ID.
      schema:
        type: integer
        example: 34567
    collectionResponseUid:
      name: responseId
      in: path
      required: true
      description: The response's unique ID.
      schema:
        type: string
        format: uid
        example: 12345678-cc364734-7dfd-4bfc-897d-be763dcdbb07
    collectionUid:
      name: collectionId
      in: path
      required: true
      description: The collection's unique ID.
      schema:
        type: string
        format: uid
        example: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
    collectionRequestUid:
      name: requestId
      in: path
      required: true
      description: The request's unique ID.
      schema:
        type: string
        format: uid
        example: 12345678-c82dd02c-4870-4907-8fcb-593a876cf05b
    apiId:
      name: apiId
      in: path
      required: true
      description: The API's ID.
      schema:
        type: string
        example: 90ca9f5a-c4c4-11ed-afa1-0242ac120002
    collectionFolderUid:
      name: folderId
      in: path
      required: true
      description: The folder's unique ID.
      schema:
        type: string
        format: uid
        example: 12345678-65a99e60-8e0a-4b6e-b79c-7d8264cc5caa
  requestBodies:
    commentCreateUpdate:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/commentCreateUpdate'
          examples:
            Create Comment:
              value:
                body: This is an example.
            Tag User in Comment:
              value:
                body: This is an example. @alex-cruz
                tags:
                  '@alex-cruz':
                    type: user
                    id: 12345678
  securitySchemes:
    PostmanApiKey:
      type: apiKey
      in: header
      name: x-api-key
    scimApiKey:
      type: apiKey
      in: header
      name: Authorization
      description: A valid [SCIM API key](https://learning.postman.com/docs/administration/scim-provisioning/scim-provisioning-overview/#generating-scim-api-key) for calls to SCIM endpoints.
