openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Worker Deployments (Deprecated) API
  version: 4.0.0
tags:
- name: Worker Deployments (Deprecated)
paths:
  /accounts/{account_id}/workers/deployments/by-script/{script_id}:
    get:
      deprecated: true
      operationId: worker-deployments-(-deprecated)-list-deployments
      parameters:
      - in: path
        name: script_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_script_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_deployments-list-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: List Deployments response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_deployments-list-response'
          description: List Deployments response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Deployments
      tags:
      - Worker Deployments (Deprecated)
      x-api-token-group:
      - Workers Tail Read
      - Workers Scripts Write
      - Workers Scripts Read
      x-cfDeprecation:
        description: This endpoint and its related APIs are deprecated in favor of the `/accounts/{account_id}/workers/scripts/{script_name}/versions` equivalent APIs.
        display: true
        id: worker_deployments_deprecation
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.worker.deployment.list
  /accounts/{account_id}/workers/deployments/by-script/{script_id}/detail/{deployment_id}:
    get:
      deprecated: true
      operationId: worker-deployments-(-deprecated)-get-deployment-detail
      parameters:
      - in: path
        name: deployment_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_deployment_identifier'
      - in: path
        name: script_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_script_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_deployments-single-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: Get Deployment Detail response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_deployments-single-response'
          description: Get Deployment Detail response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Deployment Detail
      tags:
      - Worker Deployments (Deprecated)
      x-api-token-group:
      - Workers Tail Read
      - Workers Scripts Write
      - Workers Scripts Read
      x-cfDeprecation:
        description: This endpoint and its related APIs are deprecated in favor of the `/accounts/{account_id}/workers/scripts/{script_name}/versions` equivalent APIs.
        display: true
        id: worker_deployments_deprecation
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.worker.deployment.read
components:
  schemas:
    workers_deployment_identifier:
      example: bcf48806-b317-4351-9ee7-36e7d557d4de
      maxLength: 36
      readOnly: true
      type: string
    workers_script_identifier:
      example: 8ee82b3a2c0f42928b8f14dae4a97121
      maxLength: 32
      readOnly: true
      type: string
    workers_deployments-single-response:
      allOf:
      - $ref: '#/components/schemas/workers_api-response-common'
      - properties:
          result:
            properties:
              id:
                example: 18f97339-c287-4872-9bdd-e2135c07ec12
                type: string
              metadata:
                example:
                  author_email: user@example.com
                  author_id: 408cbcdfd4dda4617efef40b04d168a1
                  created_on: '2022-11-08T17:19:29.176266Z'
                  modified_on: '2022-11-08T17:19:29.176266Z'
                  source: api
                type: object
              number:
                example: 1
                type: number
              resources:
                example:
                  bindings:
                  - json: example_binding
                    name: JSON_VAR
                    type: json
                  script:
                    etag: 13a3240e8fb414561b0366813b0b8f42b3e6cfa0d9e70e99835dae83d0d8a794
                    handlers:
                    - fetch
                    last_deployed_from: api
                  script_runtime:
                    usage_model: bundled
                type: object
            type: object
    workers_deployments-list-response:
      allOf:
      - $ref: '#/components/schemas/workers_api-response-common'
      - properties:
          result:
            properties:
              items:
                example:
                - id: bcf48806-b317-4351-9ee7-36e7d557d4de
                  metadata:
                    author_email: user@example.com
                    author_id: 408cbcdfd4dda4617efef40b04d168a1
                    created_on: '2022-11-15T18:25:44.442097Z'
                    modified_on: '2022-11-15T18:25:44.442097Z'
                    source: api
                  number: 2
                - id: 18f97339-c287-4872-9bdd-e2135c07ec12
                  metadata:
                    author_email: user@example.com
                    author_id: 408cbcdfd4dda4617efef40b04d168a1
                    created_on: '2022-11-08T17:30:56.968096Z'
                    modified_on: '2022-11-08T17:30:56.968096Z'
                    source: api
                  number: 1
                items:
                  $ref: '#/components/schemas/workers_version-item-short'
                type: array
              latest:
                example:
                  id: bcf48806-b317-4351-9ee7-36e7d557d4de
                  metadata:
                    author_email: user@example.com
                    author_id: 408cbcdfd4dda4617efef40b04d168a1
                    created_on: '2022-11-15T18:25:44.442097Z'
                    modified_on: '2022-11-15T18:25:44.442097Z'
                    source: api
                  number: 2
                  resources:
                    bindings:
                    - json: example_binding
                      name: JSON_VAR
                      type: json
                    script:
                      etag: 13a3240e8fb414561b0366813b0b8f42b3e6cfa0d9e70e99835dae83d0d8a794
                      handlers:
                      - fetch
                      last_deployed_from: api
                    script_runtime:
                      usage_model: bundled
                type: object
            type: object
    workers_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    workers_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/workers_messages'
        messages:
          $ref: '#/components/schemas/workers_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    workers_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    workers_version-item-short:
      properties:
        id:
          example: 18f97339-c287-4872-9bdd-e2135c07ec12
          readOnly: true
          type: string
        metadata:
          example:
            author_email: user@example.com
            author_id: 408cbcdfd4dda4617efef40b04d168a1
            created_on: '2022-11-08T17:19:29.176266Z'
            modified_on: '2022-11-08T17:19:29.176266Z'
            source: api
          readOnly: true
          type: object
        number:
          example: 1
          readOnly: true
          type: number
      type: object
    workers_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
